import Foundation
import AppKit
@testable import XTools
import Testing

struct CommandPaletteNavigationSourceContractTests {
    /// v3 contract (user decision 2026-09-13): the palette is a bounded
    /// command system. Shell commands live beside tool navigation, and
    /// preview-style rows render live output with return-to-copy. The command
    /// surface stays bounded by `CommandActionID` — no free-form script host,
    /// and sidebar-search keeps its ⌘F path instead of becoming a command.
    @Test func commandPaletteOwnsBoundedShellCommands() throws {
        let commandPalette = try readSource("Sources/XTools/AppShell/CommandPalette.swift")
        let actions = try readSource("Sources/XTools/AppShell/CommandActions.swift")
        let state = try readSource("Sources/XTools/AppShell/CommandPaletteNavigationState.swift")
        let root = try readSource("Sources/XTools/AppShell/RootView.swift")

        contains(actions, "enum CommandActionID", "Palette commands must be a bounded, shell-owned id enum")
        contains(actions, "case toggleAppearance", "Appearance cycling must be a named command")
        contains(actions, "case toggleSidebar", "Sidebar visibility must be a named command")
        contains(actions, "case openPreferences", "Preferences must be a named command")
        contains(actions, "case copyGeneratedUUID", "Preview-style copy commands must be named")
        contains(actions, "func matches(query: String) -> Bool", "Command rows must filter through one shared matcher")

        contains(state, "case command(CommandActionEntry)", "Palette rows must carry commands as a first-class projection case")
        contains(state, ".sectionTitle(\"动作\")", "Commands must render under one shared 动作 section")
        contains(state, "actions: [CommandActionEntry] = []", "Rows must keep a default action-free projection for tool-only callers")

        contains(commandPalette, "let actions: [CommandActionEntry]", "Palette must receive commands as injected values, never shell references")
        contains(commandPalette, "let onRunCommand: (CommandActionID) -> Void", "Command activation must report back through one injected closure")
        contains(commandPalette, "placeholder: \"搜索工具或命令…\"", "Palette placeholder must describe tools and commands")
        contains(commandPalette, "PaletteRowIconAnchorsKey", "v3: palette rows must expose launch-icon anchors for the title-rail continuity flight")

        contains(root, "onRunCommand: runPaletteCommand", "RootView must own command execution")
        contains(root, "baseActions: commandBaseActions", "Root must inject shell-derived base actions without observing presentation state")
        contains(actions, "static func paletteActions(", "Session command construction must recreate preview rows from stable base actions")
        contains(root, "CommandActionEntry.paletteActions(", "The overlay observer must append its session-scoped preview action through the shared constructor")
        contains(commandPalette, "let actions = CommandActionEntry.paletteActions(", "Synchronous session preparation must recreate a consumed preview command")
        contains(root, "next.previewValue = UUID().uuidString.lowercased()", "Preview payloads must refresh once per palette presentation")
        contains(root, "viewModel.consumeCommandPalettePreviewValue()", "Consumed preview payloads must expire so stale values are never copied twice")
        contains(root, "iconFlight.cancelPendingLaunch()\n        if viewModel.selectedToolID != toolID,", "Selecting the current tool must not leave an unresolved palette icon flight pending")

        doesNotContain(commandPalette, "聚焦侧边栏搜索", "Sidebar search keeps its ⌘F path and stays out of the palette")
        doesNotContain(root, "onSelectTool: selectToolFromPalette,\n                    onFocusSearch: focusSidebarSearch", "RootView must not pass focus-search action into the command palette")
        doesNotContain(root, "onSelectTool: selectToolFromPalette,\n                    onPreferences: showPreferences", "RootView must not pass preferences action into the command palette")
    }

    /// The search ranking algorithm and category-title projection are now covered
    /// by real behavior tests in `ToolNavigationProjectionTests`. This case keeps
    /// only the SwiftUI *view-structure* assertions that have no runtime-
    /// introspection equivalent: the palette must still wire projected results
    /// into a scroll reader that keeps the active row visible.
    @Test func commandPaletteKeepsActiveRowVisible() throws {
        let source = try readSource("Sources/XTools/AppShell/CommandPalette.swift")
        let nativeRows = try readSource("Sources/XTools/AppShell/CommandPaletteNativeRows.swift")
        let sessionModel = try readSource("Sources/XTools/AppShell/CommandPaletteSessionModel.swift")

        contains(sessionModel, "ToolNavigationCommandProjection(", "Command palette must drive its list from the narrow tested navigation projection")
        contains(nativeRows, "struct CommandPaletteRowAttachment: NSViewRepresentable", "Command palette must attach its merged native row behavior to the real AppKit row view")
        contains(nativeRows, "final class CommandPaletteRevealView: NSView", "Command palette reveal must use the native scroll owner behind the SwiftUI list")
        contains(source, ".id(item.id)", "Command palette rows must expose stable ids for scrolling")
        contains(nativeRows, "struct CommandPaletteRevealRequest: Equatable", "Command palette must model explicit active-row reveal requests")
        contains(source, "@State private var revealRequest: CommandPaletteRevealRequest?", "Command palette reveal requests must be explicit state, not derived from every active-id change")
        contains(source, "private(set) var sessionRevealRequest: CommandPaletteRevealRequest?", "A new session must prepare its top reveal before presentation publishes")
        contains(source, "source: .openReset,", "Opening must synchronously queue a top reveal for the new session")
        contains(source, "let revealRegistry = CommandPaletteRevealRegistry()", "The retained palette lifecycle must own the native visible-row state")
        contains(source, "private func requestActiveReveal(for source: CommandPaletteActiveChangeSource)", "Command palette must route active-row changes through an intent-aware reveal gate")
        contains(source, "let moveDecision = sessionModel.navigationState.keyboardMoveDecision(", "Command palette must delegate arrow boundary and handoff decisions to the tested pure policy")
        contains(source, "contentLifecycle.revealRegistry.visibleEdgeSelectableIndex(direction: delta)", "Command palette keyboard movement must read native visible-edge candidates on demand after manual mouse scrolling")
        contains(source, "visibleHandoffIndex: visibleHandoffIndex", "Command palette must pass native visible-edge candidates into the pure move policy")
        contains(source, "contentLifecycle.revealRegistry.isVisible(itemID:)", "Command palette must compute current active-row visibility before the pure move policy")
        contains(source, "isCurrentActiveVisible: isCurrentActiveVisible", "Command palette must pass current active-row visibility into the pure move policy")
        contains(source, "let hasPendingKeyboardRevealForCurrentActive =", "Command palette must compute latest pending reveal state before the pure move policy")
        contains(source, "contentLifecycle.revealRegistry.hasLatestPendingKeyboardReveal(itemID:)", "Command palette must pass latest pending reveal state into the pure move policy")
        contains(source, "contentLifecycle.revealRegistry.hasManualScrollAfterLatestKeyboardReveal()", "Command palette must only visible-sync after explicit manual scroll evidence, not keyboard reveal lag")
        contains(source, "case .move(let index), .alignToVisibleSelectableIndex(let index):", "Command palette must let the pure policy distinguish normal movement from visible-edge handoff")
        contains(source, "case .revealCurrent:", "Command palette boundary key-repeat may reveal the clamped active row without jumping to the opposite visible edge")
        contains(source, "session: presentationSession", "Every native row attachment and reveal request must carry its immutable presentation session")
        contains(source, "interactionEnabled: isPresentationReady", "Hidden retained rows must synchronously stop native interaction")
        contains(nativeRows, "func revealImmediately(request: CommandPaletteRevealRequest)", "Command palette reveal registry must expose a synchronous row-view reveal path for key repeat")
        contains(nativeRows, "manualScrollGenerationAtLatestKeyboardReveal = manualScrollGeneration", "Command palette must snapshot manual-scroll state when a keyboard reveal starts")
        contains(nativeRows, "guard NSApp.currentEvent?.type == .scrollWheel else { return }", "Command palette visible-edge handoff must be backed by a local scroll-wheel bounds change")
        contains(nativeRows, "registry?.isLatestRevealRequest(request) == true", "Command palette stale async reveal blocks must not scroll after a newer or replaced session request")
        contains(nativeRows, "scheduledRevealRetryRequest = request", "Command palette reveal fallback must retain at most the current request while the row attaches")
        contains(nativeRows, "let visibleRect = clipView.bounds", "Command palette visible-row sync must read the real scroll owner bounds")
        contains(nativeRows, "clipView.scroll(to: NSPoint(x: visibleRect.origin.x, y: clampedY))", "Command palette keyboard reveal must scroll the native clip view directly without animation lag")
        contains(nativeRows, "override func mouseMoved(with event: NSEvent)", "Command palette pointer activation must follow real pointer movement")
        contains(nativeRows, "options: [.mouseMoved, .activeInKeyWindow, .inVisibleRect]", "Command palette pointer activation must only react in the key window")
        contains(nativeRows, "override func hitTest(_ point: NSPoint) -> NSView?", "Command palette pointer tracking overlay must not intercept row clicks")
        contains(nativeRows, "func suspend(session: Int)", "Closing a retained palette must suspend native observers and tracking synchronously")
        contains(nativeRows, "func resume(session: Int)", "A new presentation session must explicitly resume retained native rows")
        doesNotContain(nativeRows, "CommandPaletteMouseMoveActivation", "Command palette rows must not keep a second native hover bridge")
        doesNotContain(source, "ScrollViewReader", "Command palette must not depend on SwiftUI proxy reveal for key-repeat list scrolling")
        doesNotContain(source, "proxy.scrollTo", "Command palette must use the native scroll owner, matching DocSearch-style row reveal")
        doesNotContain(source, ".onChange(of: activeItemID)", "Command palette must not scroll on every active-id change because pointer movement also changes the active row")
        doesNotContain(source, "proxy.scrollTo(activeID, anchor: .center)", "Command palette must not always center active rows")
        doesNotContain(source, "visibleSelectableRowCapacity", "Command palette must not hand-estimate the visible row count because key-repeat scrolling must follow the real scroll container")
        doesNotContain(source, "estimatedVisibleSelectableRange", "Command palette must not suppress keyboard reveal with a stale visible-range estimate")
        doesNotContain(source, "shouldRevealActiveRow", "Command palette must delegate visibility decisions to the scroll container instead of duplicating viewport math")
        doesNotContain(source, "withAnimation(.easeInOut(duration: 0.12))", "Command palette reveal must not animate hover-sensitive list scrolling")
        doesNotContain(nativeRows, "Timer.", "Command palette reveal must stay event-driven and avoid timer polling")
        doesNotContain(nativeRows, "GeometryReader", "Command palette reveal must not add continuous geometry measurement")
        doesNotContain(nativeRows, "NSEvent.addLocalMonitorForEvents", "Command palette ordinary navigation must remain field-scoped, not global-monitor driven")
        doesNotContain(source, ".onHover { hovering in", "Command palette rows must not use hover-enter to drive active state during key-repeat scrolling")
        doesNotContain(nativeRows, "override func mouseMoved(with event: NSEvent) {\n        onMouseMove?()\n    }", "Command palette rows must not activate from synthetic or stationary pointer delivery")
    }

    /// Active-row projection, selectable rows, pointer movement, reset, and activation are
    /// covered by real behavior tests in `CommandPaletteSearchTests`. This case
    /// keeps only the SwiftUI/AppKit *wiring* that has no runtime-introspection
    /// equivalent: the palette must route arrow/Return/Escape through an AppKit
    /// field (SwiftUI's TextField swallows them), and wire all input gestures to
    /// the tested palette state.
    @Test func commandPaletteKeyboardNavigationActivatesActiveTool() throws {
        let source = try readSource("Sources/XTools/AppShell/CommandPalette.swift")
        let sessionModel = try readSource("Sources/XTools/AppShell/CommandPaletteSessionModel.swift")
        let searchLifecycle = try readSource("Sources/XTools/Shared/Components/AppKitSearchFieldLifecycle.swift")
        let trace = try readSource("Sources/XTools/AppShell/CommandPaletteTrace.swift")
        let root = try readSource("Sources/XTools/AppShell/RootView.swift")

        contains(root, "let commandPalettePresentation = CommandPalettePresentationModel()", "RootViewModel must keep presentation notifications in a separate non-forwarded object")
        contains(root, "@Published private var state = State()", "Palette presentation changes must publish one atomic state value")
        contains(root, "var commandPaletteFocusToken: Int { commandPalettePresentation.focusToken }", "RootViewModel must preserve its command-palette focus-token facade")
        contains(root, "var commandPalettePresentationSession: Int { commandPalettePresentation.session }", "RootViewModel must preserve its presentation-session facade")
        contains(root, "next.session += 1", "Closing the palette must invalidate prior presentation sessions")
        contains(root, "lifecycle?.commandPaletteDidOpen(\n            session: nextSession,", "A retained palette must prepare its new session synchronously before presentation")
        contains(root, "func focusCommandPalette()", "RootViewModel must expose a command-palette refocus action")
        contains(root, "if state.shows {\n            focus()", "Command-K while already open must refocus without resetting the query")
        contains(root, "focusToken: presentation.focusToken", "The overlay observer must pass its focus token into the command palette")
        contains(root, "&& presentation.session == presentationSession", "Palette focus retries must remain scoped to the presentation that created the port")
        contains(root, "onRequestFocus: viewModel.focusCommandPalette", "Command palette local controls must be able to refocus the search field")
        contains(root, ".allowsHitTesting(isPresented)", "A closing palette must immediately leave hit testing")
        contains(root, ".accessibilityHidden(!isPresented)", "A closing palette must immediately leave the accessibility tree")
        contains(root, "if presentation.hasPresented {", "The palette content tree must remain mounted after its first presentation")
        doesNotContain(root, ".id(presentationSession)", "A new session must not replace the retained palette content tree")
        doesNotContain(root, "@Published var showsCommandPalette", "Palette presentation changes must not invalidate the full RootView")
        doesNotContain(root, "commandText", "Palette query must remain local to one mounted presentation")

        contains(source, "@StateObject private var sessionModel: CommandPaletteSessionModel", "Command palette must keep one presentation-local query and active-row owner")
        contains(sessionModel, "@Published private var state: State", "Query, navigation, snapshot, and session must publish as one atomic value")
        contains(sessionModel, "var snapshot: CommandPaletteRowSnapshot { state.snapshot }", "Command palette must cache the query-matched row snapshot outside body evaluation")
        contains(sessionModel, "next.snapshot = snapshot", "Native edits must synchronously replace the current query snapshot")
        contains(sessionModel, "next.navigationState.resetActiveRow()", "Filtering must reset the active row in the same synchronous update")
        contains(source, "let inputSession = sessionModel.session", "Native field callbacks must capture the immutable session represented by that field")
        contains(source, "inputSession == presentationSession", "Stale retained field callbacks must reject a replaced presentation")
        contains(source, ".id(inputSession)", "Only the native search field must receive a fresh identity each session")
        contains(source, "revealRegistry.suspend(session: session)", "Closing must synchronously suspend retained native rows")
        contains(source, "transaction.animation = nil", "Session row changes must not inherit the outer modal animation")
        contains(root, "progress: presentation.shows ? 1 : 0", "Visible presentation progress must derive directly from the stable presentation shell")
        contains(source, "selectableIndex: snapshot.selectableIndex(of: item)", "Command palette rows must consume precomputed selectable indexes")
        contains(source, "sessionModel.navigationState.keyboardMoveDecision(", "Command palette arrows must use the tested active-row movement policy")
        contains(source, "private func activateActive()", "Command palette must activate the active row on submit")
        contains(source, "private func setActiveItem(_ item: CommandPaletteRowProjection)", "Command palette pointer movement must update the same active row as keyboard navigation")
        contains(source, "guard item.id != sessionModel.navigationState.activeRowID(in: snapshot) else { return }", "Command palette pointer movement must avoid redundant active-state writes while moving inside the already-active row")
        contains(source, "private func activate(_ item: CommandPaletteRowProjection)", "Command palette mouse clicks and keyboard submit must share the same activation path")
        contains(source, "requestActiveReveal(for: .keyboard(delta: delta))", "Keyboard movement must request active-row reveal")
        contains(source, "requestActiveReveal(for: .queryReset, in: sessionModel.snapshot)", "Filtering must request a stable active-row reveal from the same row snapshot after reset")
        contains(source, "requestActiveReveal(for: .pointerMove)", "Pointer-driven active changes must route through the same source policy that does not request scrolling")
        contains(source, "activateActive()", "Command palette Return key must jump to the active tool")
        contains(source, "struct CommandPaletteSearchField: NSViewRepresentable", "Command palette must use an AppKit-backed field for reliable keyboard handling")
        contains(source, "let focusToken: Int", "Command palette search field must accept explicit refocus requests")
        contains(source, "AppKitSearchFieldLifecycle.update(", "Command palette search field must delegate focus-token updates to the shared lifecycle")
        contains(source, "CommandPaletteTrace.appeared(session: presentationSession)", "Debug palette measurement must observe the real presented view")
        contains(source, "CommandPaletteTrace.observeNativeReady(", "Opt-in diagnostics must measure actual native field layout and editor ownership")
        contains(source, "processedFocusToken: nil", "Command palette must preserve its first focus request")
        contains(source, "focusRetryDelays: [0.05, 0.15]", "Command palette must preserve both delayed focus retries")
        contains(source, "observer: CommandPaletteTrace.focusAttemptObserver(", "Command palette focus diagnostics must stay scoped to its presentation session")
        contains(source, "session: presentationSession", "Command palette focus diagnostics must use the mounted presentation session")
        contains(source, "canRequestFocus: canRequestFocus", "Command palette must pass its live presentation validity into the search lifecycle")
        contains(source, "static func dismantleNSView", "Command palette search must invalidate pending focus work when its representable is dismantled")
        contains(searchLifecycle, "DispatchQueue.main.asyncAfter", "Shared lifecycle must retry focus after SwiftUI attaches the field to a window")
        contains(searchLifecycle, "guard isValid(), let textField, let window = textField.window,", "Every untraced focus attempt must reject stale generations and closed presentations")
        contains(searchLifecycle, "guard !state.succeeded else { return }", "A successful focus request must not reclaim first responder in a delayed retry")
        contains(searchLifecycle, "window.firstResponder === editor", "Focus success must require the search field's actual field editor")
        contains(searchLifecycle, "func invalidateFocusRequests()", "Shared search lifecycle must expose a deterministic dismantle invalidation boundary")
        contains(trace, "TOOLS_COMMAND_PALETTE_FOCUS_TRACE", "Focus-attempt diagnostics must require a dedicated opt-in switch")
        contains(trace, "TOOLS_COMMAND_PALETTE_READY_TRACE", "Native-ready diagnostics must require a dedicated opt-in switch")
        contains(source, ".frame(maxWidth: .infinity, maxHeight: .infinity)", "Command palette native search field must fill its 24pt port")
        contains(source, "static let searchClearButtonSize: CGFloat = 24", "Command palette clear control must meet the shared 24pt pointer target")
        contains(source, "if !sessionModel.query.isEmpty {", "Command palette clear control must leave the accessibility tree when no clearing action is available")
        doesNotContain(source, ".opacity(query.isEmpty ? 0 : 1)", "Command palette clear control must not remain as an invisible accessibility element")
        doesNotContain(source, ".frame(height: 24)\n                .iBeamCursorOnHover()", "Command palette search must not keep a false outer I-beam target")
        doesNotContain(source, "private func requestFocus", "Command palette must not duplicate shared focus scheduling")
        contains(source, "let search: AppKitSearchFieldCoordinator", "The representable wrapper must delegate editing and focus mechanics to the shared coordinator")
        contains(source, "textView.hasMarkedText()", "Command palette must let IME marked-text composition handle Return/arrows/Escape")
        contains(source, "case #selector(NSResponder.moveUp(_:)):", "Command palette search field must intercept the Up arrow before NSTextField consumes it")
        contains(source, "case #selector(NSResponder.moveDown(_:)):", "Command palette search field must intercept the Down arrow before NSTextField consumes it")
        contains(source, "case #selector(NSResponder.insertNewline(_:)):", "Command palette search field must intercept Return for active-row activation")
        contains(source, "case #selector(NSResponder.cancelOperation(_:)):", "Command palette search field must intercept Escape for dismissal")
        contains(source, "moveActive(by: -1)", "Command palette Up arrow must move the active row upward")
        contains(source, "moveActive(by: 1)", "Command palette Down arrow must move the active row downward")
        contains(source, "guard isInputSessionLive(inputSession) else { return }", "Native query edits and commands must reject stale presentations")
        contains(source, "onMouseMove: { setActiveItem(item) }", "Command palette mouse movement must use the same active row as Return activation")
        contains(source, "onRequestFocus()", "Command palette clear button must return focus to the search field")
        contains(source, "Text(\"没有匹配的工具或命令\")", "Command palette must show a no-results state for empty result sets")
        contains(source, "activate(item)", "Command palette rows must call the shared activation path")
    }

    @Test func sidebarGroupsUsePersistentDisclosureSections() throws {
        let root = try readSource("Sources/XTools/AppShell/RootView.swift")
        let sidebar = try readSource("Sources/XTools/AppShell/SidebarView.swift")
        let sidebarEntries = try readSource("Sources/XTools/AppShell/SidebarNavigationEntry.swift")
        let sidebarRenderer = try readSource("Sources/XTools/AppShell/SidebarNavigationList.swift")
        let store = try readSource("Sources/XTools/AppShell/SidebarSectionExpansionStore.swift")
        let disclosureStore = try readSource("Sources/XTools/Shared/DisclosureExpansionStore.swift")
        let actions = try readSource("Sources/XTools/AppShell/ToolNavigationActions.swift")

        contains(root, "@StateObject private var sidebarSections = SidebarSectionExpansionStore()", "RootView must own sidebar section expansion as app-shell state")
        contains(root, "private var navigationActions: ToolNavigationActions", "RootView must compose the app-shell navigation action seam")
        contains(root, "ToolNavigationActions(", "RootView must construct navigation actions from shell stores")
        contains(root, "_ = navigationActions.selectTool(toolID)\n        closeCommandPaletteAnimated()", "v3: palette jumps use the shared navigation path plus one animated close transaction")
        contains(root, "guard let nowFavorite = navigationActions.toggleFavorite(toolID) else { return }", "Titlebar favorite changes must use the shared navigation action path")

        doesNotContain(sidebar, "@ObservedObject var sidebarSections: SidebarSectionExpansionStore", "Sidebar must not own persistent section expansion implementation knowledge")
        contains(sidebar, "let isSectionExpanded: (ToolNavigationSection) -> Bool", "Sidebar must consume section expansion through the navigation seam")
        contains(sidebar, "let onToggleSection: (ToolNavigationSection) -> Void", "Sidebar group disclosure must call a high-level section action")
        contains(sidebar, "private var isSearchActive: Bool", "Sidebar must detect search mode before applying disclosure collapse")
        contains(sidebarEntries, "isSearchActive || isSectionExpanded(group.section)", "Search results must stay visible even when a group is collapsed")
        contains(sidebar, "guard !isSearchActive else { return }", "Search mode must not hide matching tool rows through section collapse")
        contains(sidebar, "struct SidebarGroupHeader: View", "Sidebar group headers must be first-class disclosure controls")
        contains(sidebar, "static let disclosureGroupSpacing: CGFloat = 5", "Collapsed sidebar disclosure groups must use a compact list rhythm")
        contains(sidebar, "static let toolRowHorizontalPadding: CGFloat = 9", "Sidebar tool rows must keep a named base padding for selection rail alignment")
        contains(sidebar, "static let toolRowHierarchyIndent: CGFloat = 16", "Sidebar child tool rows must use a named hierarchy indent")
        contains(sidebarRenderer, "systemImage: group.systemImage", "Sidebar disclosure headers must include the projected category icon")
        contains(sidebar, "Image(systemName: \"chevron.right\")", "Sidebar disclosure headers must use a stable chevron glyph")
        contains(sidebar, ".rotationEffect(.degrees(isExpanded ? 90 : 0))", "Sidebar disclosure state must be shown through chevron rotation instead of glyph swapping")
        contains(sidebar, ".padding(.leading, SidebarMetrics.toolRowHorizontalPadding + SidebarMetrics.toolRowHierarchyIndent)", "Sidebar child row content must indent under the group title without shrinking the row background")
        contains(sidebar, ".padding(.trailing, SidebarMetrics.toolRowHorizontalPadding)", "Sidebar child row trailing padding must keep the existing row action affordance space")
        contains(sidebar, ".offset(x: -SidebarMetrics.toolRowHorizontalPadding)", "Sidebar selection rail must stay aligned to the full row background, not the indented content")
        contains(sidebar, ".accessibilityValue(shouldHighlight ? \"已选择\" : \"\")", "Sidebar tool rows must expose the selected state to accessibility")
        contains(sidebar, "SidebarNavigationEntryProjection.entries(", "Sidebar disclosure state must project into one tested flat identity domain")
        contains(sidebar, "SidebarNavigationList(configuration:", "Sidebar headers and tools must render through one stable flat identity domain")
        doesNotContain(sidebar, "ForEach(sidebarEntries)", "Sidebar disclosure must not structurally insert and remove SwiftUI rows")
        contains(sidebar, "static let interRowSpacing: CGFloat = 1", "Flat sidebar tool rows must preserve the existing one-point row rhythm through an independent track")
        doesNotContain(sidebar, "ToolDisclosureBody(", "Cross-group tool moves must not be split across clipped per-group disclosure bodies")
        doesNotContain(sidebar, ".frame(height: isExpanded ? nil : 0, alignment: .top)", "Sidebar disclosure rows must not collapse by compressing their real content")
        contains(sidebar, ".accessibilityValue(isExpanded ? \"已展开\" : \"已收起\")", "Disclosure headers must expose expanded/collapsed accessibility state")
        contains(sidebar, "if hoverState.isHovered {\n            return ToolTheme.hoverFill", "Sidebar disclosure headers may show hover fill but must not inherit child selection fill")
        doesNotContain(sidebar, ".move(edge: .top)", "Sidebar disclosure content must not fly in or out from the top")
        doesNotContain(sidebar, ".textCase(.uppercase)", "Sidebar category labels must preserve Chinese labels and normal Web casing")
        doesNotContain(sidebar, ".tracking(0.8)", "Sidebar category labels must not use caption-style letter spacing")
        doesNotContain(sidebar, "isActive: isActive", "Sidebar disclosure headers must not inherit selected child section state")
        doesNotContain(sidebar, "let isActive = projection.selectedSection == group.section", "Sidebar group headers must not turn selected child ownership into parent-row selection")
        contains(sidebarRenderer, "onSelectTool(item.id)", "Selecting a row tool must call the shared navigation action path")
        contains(sidebarRenderer, "onToggleFavorite(item.id)", "Sidebar favorite toggles must call the shared navigation action path")
        contains(sidebar, ".accessibilityIdentifier(\"sidebar.favorite.\\(toolID.rawValue)\")", "Sidebar favorite controls must keep stable ToolID-scoped accessibility identity")
        doesNotContain(sidebar, "sidebarSections.expand(item.section.groupID)", "Sidebar must not duplicate section expansion rules")
        doesNotContain(sidebar, "private func toggleFavorite(for item: ToolNavigationItem)", "Sidebar must not duplicate favorite migration rules")

        contains(actions, "func selectTool(_ toolID: ToolID, dismissCommandPalette: Bool = false) -> Bool", "Navigation actions must own tool selection")
        contains(actions, "func toggleFavorite(_ toolID: ToolID) -> Bool?", "Navigation actions must own favorite migration")
        contains(actions, "sidebarSections.expand(section.groupID)", "Navigation actions must expand the section that owns the tool")
        contains(actions, "private func section(for toolID: ToolID) -> ToolNavigationSection?", "Navigation actions must centralize tool-to-section resolution")

        contains(disclosureStore, "class PersistentDisclosureExpansionStore: ObservableObject", "Sidebar section state must reuse the shared disclosure persistence owner")
        contains(store, "final class SidebarSectionExpansionStore: PersistentDisclosureExpansionStore", "Sidebar section expansion must keep its named shell store on top of the shared persistence owner")
        contains(store, "static let storageKey = \"tools.sidebar.collapsedSections.v1\"", "Sidebar section state must persist under a versioned shell preference key")
        contains(disclosureStore, "@Published private(set) var collapsedGroupIDs: Set<String>", "Store must persist collapsed ids so new sections default to visible")
        contains(disclosureStore, "defaults.set(collapsedGroupIDs.sorted(), forKey: storageKey)", "Collapsed section ids must be persisted in stable order")
    }
}
