import Foundation
import AppKit
@testable import XTools
import Testing

struct CommandPaletteNavigationSourceContractTests {
    /// v3 contract (user decision 2026-09-13): the palette is a bounded
    /// command system. Shell commands live beside tool navigation, and
    /// preview-style rows render live output with return-to-copy. The command
    /// surface stays bounded by `CommandActionID` — no free-form script host,
    /// and sidebar-search keeps its ⌘F path instead of becoming a command.
    @Test func commandPaletteOwnsBoundedShellCommands() throws {
        let commandPalette = try readSource("Sources/XTools/AppShell/CommandPalette.swift")
        let actions = try readSource("Sources/XTools/AppShell/CommandActions.swift")
        let state = try readSource("Sources/XTools/AppShell/CommandPaletteNavigationState.swift")
        let root = try readSource("Sources/XTools/AppShell/RootView.swift")

        contains(actions, "enum CommandActionID", "Palette commands must be a bounded, shell-owned id enum")
        contains(actions, "case toggleAppearance", "Appearance cycling must be a named command")
        contains(actions, "case toggleSidebar", "Sidebar visibility must be a named command")
        contains(actions, "case openPreferences", "Preferences must be a named command")
        contains(actions, "case copyGeneratedUUID", "Preview-style copy commands must be named")
        contains(actions, "func matches(query: String) -> Bool", "Command rows must filter through one shared matcher")

        contains(state, "case command(CommandActionEntry)", "Palette rows must carry commands as a first-class projection case")
        contains(state, ".sectionTitle(\"动作\")", "Commands must render under one shared 动作 section")
        contains(state, "actions: [CommandActionEntry] = []", "Rows must keep a default action-free projection for tool-only callers")

        contains(commandPalette, "let actions: [CommandActionEntry]", "Palette must receive commands as injected values, never shell references")
        contains(commandPalette, "let onRunCommand: (CommandActionID) -> Void", "Command activation must report back through one injected closure")
        contains(commandPalette, "placeholder: \"搜索工具或命令…\"", "Palette placeholder must describe tools and commands")
        contains(commandPalette, "PaletteRowIconAnchorsKey", "v3: palette rows must expose launch-icon anchors for the title-rail continuity flight")

        contains(root, "onRunCommand: { runPaletteCommand($0) }", "RootView must own command execution")
        contains(root, "commandPalettePreviewValue = UUID().uuidString.lowercased()", "Preview payloads must refresh once per palette presentation")
        contains(root, "viewModel.consumeCommandPalettePreviewValue()", "Consumed preview payloads must expire so stale values are never copied twice")

        doesNotContain(commandPalette, "聚焦侧边栏搜索", "Sidebar search keeps its ⌘F path and stays out of the palette")
        doesNotContain(root, "onSelectTool: selectToolFromPalette,\n                    onFocusSearch: focusSidebarSearch", "RootView must not pass focus-search action into the command palette")
        doesNotContain(root, "onSelectTool: selectToolFromPalette,\n                    onPreferences: showPreferences", "RootView must not pass preferences action into the command palette")
    }

    /// The search ranking algorithm and category-title projection are now covered
    /// by real behavior tests in `ToolNavigationProjectionTests`. This case keeps
    /// only the SwiftUI *view-structure* assertions that have no runtime-
    /// introspection equivalent: the palette must still wire projected results
    /// into a scroll reader that keeps the active row visible.
    @Test func commandPaletteKeepsActiveRowVisible() throws {
        let source = try readSource("Sources/XTools/AppShell/CommandPalette.swift")

        contains(source, "projection.commandPaletteEntries", "Command palette must drive its list from the tested navigation projection")
        contains(source, "private struct CommandPaletteRevealAttachment: NSViewRepresentable", "Command palette must attach reveal behavior to the real AppKit row view")
        contains(source, "private final class CommandPaletteRevealView: NSView", "Command palette reveal must use the native scroll owner behind the SwiftUI list")
        contains(source, ".id(item.id)", "Command palette rows must expose stable ids for scrolling")
        contains(source, "struct CommandPaletteRevealRequest: Equatable", "Command palette must model explicit active-row reveal requests")
        contains(source, "@State private var revealRequest: CommandPaletteRevealRequest?", "Command palette reveal requests must be explicit state, not derived from every active-id change")
        contains(source, "@State private var revealRegistry = CommandPaletteRevealRegistry()", "Command palette must track the native visible row state for mouse-scroll/key-repeat handoff")
        contains(source, "private func requestActiveReveal(for source: CommandPaletteActiveChangeSource)", "Command palette must route active-row changes through an intent-aware reveal gate")
        contains(source, "let moveDecision = paletteState.keyboardMoveDecision(", "Command palette must delegate arrow boundary and handoff decisions to the tested pure policy")
        contains(source, "let visibleHandoffIndex = revealRegistry.visibleEdgeSelectableIndex(direction: delta)", "Command palette keyboard movement must read native visible-edge candidates on demand after manual mouse scrolling")
        contains(source, "visibleHandoffIndex: visibleHandoffIndex", "Command palette must pass native visible-edge candidates into the pure move policy")
        contains(source, "let isCurrentActiveVisible = previousActiveID.map(revealRegistry.isVisible(itemID:)) ?? false", "Command palette must compute current active-row visibility before the pure move policy")
        contains(source, "isCurrentActiveVisible: isCurrentActiveVisible", "Command palette must pass current active-row visibility into the pure move policy")
        contains(source, "let hasPendingKeyboardRevealForCurrentActive =", "Command palette must compute latest pending reveal state before the pure move policy")
        contains(source, "previousActiveID.map(revealRegistry.hasLatestPendingKeyboardReveal(itemID:)) ?? false", "Command palette must pass latest pending reveal state into the pure move policy")
        contains(source, "allowsVisibleHandoff: revealRegistry.hasManualScrollAfterLatestKeyboardReveal()", "Command palette must only visible-sync after explicit manual scroll evidence, not keyboard reveal lag")
        contains(source, "case .move(let index), .alignToVisibleSelectableIndex(let index):", "Command palette must let the pure policy distinguish normal movement from visible-edge handoff")
        contains(source, "case .revealCurrent:", "Command palette boundary key-repeat may reveal the clamped active row without jumping to the opposite visible edge")
        contains(source, "revealRegistry.markKeyboardRevealPending(itemID: activeID, token: revealRequestToken)", "Command palette key-repeat handoff must wait for the latest keyboard reveal before treating the active row as offscreen")
        contains(source, "revealRegistry.revealImmediately(request: request)", "Command palette key-repeat reveal must keep up with autorepeat instead of waiting for SwiftUI to coalesce the next view update")
        contains(source, "func revealImmediately(request: CommandPaletteRevealRequest)", "Command palette reveal registry must expose a synchronous row-view reveal path for key repeat")
        contains(source, "manualScrollGenerationAtLatestKeyboardReveal = manualScrollGeneration", "Command palette must snapshot manual-scroll state when a keyboard reveal starts")
        contains(source, "guard NSApp.currentEvent?.type == .scrollWheel else { return }", "Command palette visible-edge handoff must be backed by a local scroll-wheel bounds change")
        contains(source, "func hasManualScrollAfterLatestKeyboardReveal() -> Bool", "Command palette must expose explicit manual-scroll evidence to the keyboard move policy")
        contains(source, "pendingKeyboardReveal?.itemID == itemID", "Command palette must suppress visible-edge handoff while the same active row has an unfinished keyboard reveal")
        contains(source, "pendingKeyboardReveal?.token == latestRevealRequestToken", "Command palette must tie pending keyboard reveal state to the latest request token")
        contains(source, "if pendingKeyboardReveal?.token != token {\n            pendingKeyboardReveal = nil\n        }", "Command palette must clear stale pending reveal state when a newer reveal supersedes it")
        contains(source, "registry.isLatestRevealRequest(request)", "Command palette stale async reveal blocks must not scroll after a newer key-repeat request")
        contains(source, "registry.finishKeyboardReveal(request: request)", "Command palette must clear pending key-repeat reveal state only after the matching latest row reveal runs")
        contains(source, "private final class CommandPaletteRevealRegistry: NSObject", "Command palette visible-row sync must be owned by the narrow native reveal bridge")
        contains(source, "private var scheduledRevealRetryToken = 0", "Command palette reveal fallback must not spin if SwiftUI asks before the row view is attached")
        contains(source, "guard scheduledRevealRetryToken != request.token else { return }", "Command palette reveal fallback must schedule at most one attach retry per token")
        contains(source, "let visibleRect = scrollView.contentView.bounds", "Command palette visible-row sync must read the real scroll owner bounds")
        contains(source, "let rowRect = view.convert(view.bounds, to: documentView)", "Command palette visible-row sync must compare native row geometry against the visible document rect")
        contains(source, "view.reveal(request: revealRequest)", "Command palette must scroll only when an explicit reveal request reaches its matching row")
        contains(source, "case .keyboardEdge(let delta):", "Keyboard reveal must carry direction so key repeat can follow the visible edge")
        contains(source, "scrollToKeyboardEdge(delta: delta)", "Keyboard reveal must edge-follow instead of only ensuring minimum visibility")
        contains(source, "rowRect.maxY > visibleRect.maxY", "Down key repeat must scroll when the active row bottom passes the visible bottom")
        contains(source, "rowRect.maxY - visibleRect.height", "Down key repeat must pin the active row bottom to the visible bottom")
        contains(source, "rowRect.minY < visibleRect.minY", "Up key repeat must scroll when the active row top passes the visible top")
        contains(source, "clipView.scroll(to: NSPoint(x: visibleRect.origin.x, y: clampedY))", "Command palette keyboard reveal must scroll the native clip view directly without animation lag")
        contains(source, "scrollView.reflectScrolledClipView(clipView)", "Query reset must update the native scroll view rather than a SwiftUI proxy")
        contains(source, "private struct CommandPaletteMouseMoveActivation: NSViewRepresentable", "Command palette pointer activation must use a narrow AppKit mouse-move bridge")
        contains(source, "override func mouseMoved(with event: NSEvent)", "Command palette pointer activation must follow DocSearch-style mouse movement, not hover-enter")
        contains(source, "@State private var pointerMovementTracker = CommandPalettePointerMovementTracker()", "Command palette must share pointer movement state across all rows")
        contains(source, "pointerMovementTracker: pointerMovementTracker", "Command palette rows must receive the shared pointer movement tracker")
        contains(source, "var pointerMovementTracker: CommandPalettePointerMovementTracker?", "Command palette AppKit tracking views must not own per-row pointer movement state")
        contains(source, "pointerMovementTracker?.reset(to: window.mouseLocationOutsideOfEventStream)", "Command palette pointer tracking must seed a stationary-pointer baseline from the current window location")
        contains(source, "guard pointerMovementTracker?.acceptsMouseMoved(at: event.locationInWindow) == true else", "Command palette pointer activation must ignore mouse-move events that keep the same window coordinate")
        contains(source, "NSTrackingArea(", "Command palette pointer activation must be driven by an AppKit tracking area")
        contains(source, "options: [.mouseMoved, .activeInKeyWindow, .inVisibleRect]", "Command palette pointer activation must only react to real mouse movement in the key window")
        contains(source, "override func hitTest(_ point: NSPoint) -> NSView?", "Command palette pointer tracking overlay must not intercept row clicks")
        doesNotContain(source, "ScrollViewReader", "Command palette must not depend on SwiftUI proxy reveal for key-repeat list scrolling")
        doesNotContain(source, "proxy.scrollTo", "Command palette must use the native scroll owner, matching DocSearch-style row reveal")
        doesNotContain(source, ".onChange(of: activeItemID)", "Command palette must not scroll on every active-id change because pointer movement also changes the active row")
        doesNotContain(source, "proxy.scrollTo(activeID, anchor: .center)", "Command palette must not always center active rows")
        doesNotContain(source, "visibleSelectableRowCapacity", "Command palette must not hand-estimate the visible row count because key-repeat scrolling must follow the real scroll container")
        doesNotContain(source, "estimatedVisibleSelectableRange", "Command palette must not suppress keyboard reveal with a stale visible-range estimate")
        doesNotContain(source, "shouldRevealActiveRow", "Command palette must delegate visibility decisions to the scroll container instead of duplicating viewport math")
        doesNotContain(source, "withAnimation(.easeInOut(duration: 0.12))", "Command palette reveal must not animate hover-sensitive list scrolling")
        doesNotContain(source, "Timer.", "Command palette reveal must stay event-driven and avoid timer polling")
        doesNotContain(source, "GeometryReader", "Command palette reveal must not add continuous geometry measurement")
        doesNotContain(source, "NSEvent.addLocalMonitorForEvents", "Command palette ordinary navigation must remain field-scoped, not global-monitor driven")
        doesNotContain(source, ".onHover { hovering in", "Command palette rows must not use hover-enter to drive active state during key-repeat scrolling")
        doesNotContain(source, "private var pointerMovement = CommandPalettePointerMovementState()", "Command palette rows must not keep independent pointer baselines")
        doesNotContain(source, "override func mouseMoved(with event: NSEvent) {\n        onMouseMove?()\n    }", "Command palette rows must not activate from synthetic/stationary mouse-move delivery during keyboard scrolling")
    }

    /// Active-row projection, selectable rows, pointer movement, reset, and activation are
    /// covered by real behavior tests in `CommandPaletteSearchTests`. This case
    /// keeps only the SwiftUI/AppKit *wiring* that has no runtime-introspection
    /// equivalent: the palette must route arrow/Return/Escape through an AppKit
    /// field (SwiftUI's TextField swallows them), and wire all input gestures to
    /// the tested palette state.
    @Test func commandPaletteKeyboardNavigationActivatesActiveTool() throws {
        let source = try readSource("Sources/XTools/AppShell/CommandPalette.swift")
        let searchLifecycle = try readSource("Sources/XTools/Shared/Components/AppKitSearchFieldLifecycle.swift")
        let root = try readSource("Sources/XTools/AppShell/RootView.swift")

        contains(root, "@Published private(set) var commandPaletteFocusToken = 0", "RootViewModel must expose a command-palette focus token")
        contains(root, "@Published private(set) var commandPalettePresentationSession = 0", "RootViewModel must expose a monotonic palette presentation session")
        contains(root, "commandPalettePresentationSession += 1", "Opening and closing the palette must invalidate prior presentation sessions")
        contains(root, "func focusCommandPalette()", "RootViewModel must expose a command-palette refocus action")
        contains(root, "if !showsCommandPalette", "Command-K while already open must refocus without resetting the query")
        contains(root, "focusToken: viewModel.commandPaletteFocusToken", "RootView must pass the focus token into the command palette")
        contains(root, "viewModel.commandPalettePresentationSession == presentationSession", "Palette focus retries must remain scoped to the presentation that created the port")
        contains(root, "onRequestFocus: viewModel.focusCommandPalette", "Command palette local controls must be able to refocus the search field")

        contains(source, "@State private var paletteState = CommandPaletteNavigationState()", "Command palette must keep one tested active-row state")
        contains(source, "CommandPaletteNavigationState.snapshot(", "Command palette must project one tested row/index snapshot per body evaluation")
        contains(source, "selectableIndex: snapshot.selectableIndex(of: item)", "Command palette rows must consume precomputed selectable indexes")
        contains(source, "paletteState.keyboardMoveDecision(", "Command palette arrows must use the tested active-row movement policy")
        contains(source, "private func activateActive()", "Command palette must activate the active row on submit")
        contains(source, "private func setActiveItem(_ item: CommandPaletteRowProjection)", "Command palette pointer movement must update the same active row as keyboard navigation")
        contains(source, "guard item.id != paletteState.activeRowID(in: snapshot) else { return }", "Command palette pointer movement must avoid redundant active-state writes while moving inside the already-active row")
        contains(source, "private func activate(_ item: CommandPaletteRowProjection)", "Command palette mouse clicks and keyboard submit must share the same activation path")
        contains(source, "requestActiveReveal(for: .keyboard(delta: delta))", "Keyboard movement must request active-row reveal")
        contains(source, "requestActiveReveal(for: .queryReset, in: paletteSnapshot)", "Filtering must request a stable active-row reveal from the same row snapshot after reset")
        contains(source, "requestActiveReveal(for: .pointerMove)", "Pointer-driven active changes must route through the same source policy that does not request scrolling")
        contains(source, "onSubmit: activateActive", "Command palette Return key must jump to the active tool")
        contains(source, "struct CommandPaletteSearchField: NSViewRepresentable", "Command palette must use an AppKit-backed field for reliable keyboard handling")
        contains(source, "let focusToken: Int", "Command palette search field must accept explicit refocus requests")
        contains(source, "AppKitSearchFieldLifecycle.update(", "Command palette search field must delegate focus-token updates to the shared lifecycle")
        contains(source, "CommandPaletteTrace.appeared(session: presentationSession)", "Debug palette measurement must observe the real presented view")
        contains(source, "processedFocusToken: nil", "Command palette must preserve its first focus request")
        contains(source, "focusRetryDelays: [0.05, 0.15]", "Command palette must preserve both delayed focus retries")
        contains(source, "canRequestFocus: canRequestSearchFocus", "Command palette must pass its live presentation validity into the search lifecycle")
        contains(source, "static func dismantleNSView", "Command palette search must invalidate pending focus work when its representable is dismantled")
        contains(searchLifecycle, "DispatchQueue.main.asyncAfter", "Shared lifecycle must retry focus after SwiftUI attaches the field to a window")
        contains(searchLifecycle, "guard isValid() else { return }", "Every delayed focus attempt must reject stale generations and closed presentations")
        contains(searchLifecycle, "func invalidateFocusRequests()", "Shared search lifecycle must expose a deterministic dismantle invalidation boundary")
        contains(source, ".frame(maxWidth: .infinity, maxHeight: .infinity)", "Command palette native search field must fill its 24pt port")
        contains(source, "static let searchClearButtonSize: CGFloat = 24", "Command palette clear control must meet the shared 24pt pointer target")
        contains(source, "if !query.isEmpty {", "Command palette clear control must leave the accessibility tree when no clearing action is available")
        doesNotContain(source, ".opacity(query.isEmpty ? 0 : 1)", "Command palette clear control must not remain as an invisible accessibility element")
        doesNotContain(source, ".frame(height: 24)\n                .iBeamCursorOnHover()", "Command palette search must not keep a false outer I-beam target")
        doesNotContain(source, "private func requestFocus", "Command palette must not duplicate shared focus scheduling")
        doesNotContain(source, "final class Coordinator", "Command palette must not duplicate the shared coordinator")
        contains(source, "textView.hasMarkedText()", "Command palette must let IME marked-text composition handle Return/arrows/Escape")
        contains(source, "case #selector(NSResponder.moveUp(_:)):", "Command palette search field must intercept the Up arrow before NSTextField consumes it")
        contains(source, "case #selector(NSResponder.moveDown(_:)):", "Command palette search field must intercept the Down arrow before NSTextField consumes it")
        contains(source, "case #selector(NSResponder.insertNewline(_:)):", "Command palette search field must intercept Return for active-row activation")
        contains(source, "case #selector(NSResponder.cancelOperation(_:)):", "Command palette search field must intercept Escape for dismissal")
        contains(source, "onMoveUp: { moveActive(by: -1) }", "Command palette Up arrow must move the active row upward")
        contains(source, "onMoveDown: { moveActive(by: 1) }", "Command palette Down arrow must move the active row downward")
        contains(source, ".onChange(of: query) { _ in", "Command palette must react when filtering changes")
        contains(source, "paletteState.resetActiveRow()", "Command palette must reset the active row to the first result after query changes")
        contains(source, "onMouseMoveActive: { setActiveItem(item) }", "Command palette mouse movement must use the same active row as Return activation")
        contains(source, "onRequestFocus()", "Command palette clear button must return focus to the search field")
        contains(source, "Text(\"没有匹配的工具或命令\")", "Command palette must show a no-results state for empty result sets")
        contains(source, "activate(item)", "Command palette rows must call the shared activation path")
    }

    @Test func sidebarGroupsUsePersistentDisclosureSections() throws {
        let root = try readSource("Sources/XTools/AppShell/RootView.swift")
        let sidebar = try readSource("Sources/XTools/AppShell/SidebarView.swift")
        let sidebarEntries = try readSource("Sources/XTools/AppShell/SidebarNavigationEntry.swift")
        let sidebarRenderer = try readSource("Sources/XTools/AppShell/SidebarNavigationList.swift")
        let store = try readSource("Sources/XTools/AppShell/SidebarSectionExpansionStore.swift")
        let disclosureStore = try readSource("Sources/XTools/Shared/DisclosureExpansionStore.swift")
        let actions = try readSource("Sources/XTools/AppShell/ToolNavigationActions.swift")

        contains(root, "@StateObject private var sidebarSections = SidebarSectionExpansionStore()", "RootView must own sidebar section expansion as app-shell state")
        contains(root, "private var navigationActions: ToolNavigationActions", "RootView must compose the app-shell navigation action seam")
        contains(root, "ToolNavigationActions(", "RootView must construct navigation actions from shell stores")
        contains(root, "_ = navigationActions.selectTool(toolID)\n        closeCommandPaletteAnimated()", "v3: palette jumps use the shared navigation path plus one animated close transaction")
        contains(root, "guard let nowFavorite = navigationActions.toggleFavorite(toolID) else { return }", "Titlebar favorite changes must use the shared navigation action path")

        doesNotContain(sidebar, "@ObservedObject var sidebarSections: SidebarSectionExpansionStore", "Sidebar must not own persistent section expansion implementation knowledge")
        contains(sidebar, "let isSectionExpanded: (ToolNavigationSection) -> Bool", "Sidebar must consume section expansion through the navigation seam")
        contains(sidebar, "let onToggleSection: (ToolNavigationSection) -> Void", "Sidebar group disclosure must call a high-level section action")
        contains(sidebar, "private var isSearchActive: Bool", "Sidebar must detect search mode before applying disclosure collapse")
        contains(sidebarEntries, "isSearchActive || isSectionExpanded(group.section)", "Search results must stay visible even when a group is collapsed")
        contains(sidebar, "guard !isSearchActive else { return }", "Search mode must not hide matching tool rows through section collapse")
        contains(sidebar, "struct SidebarGroupHeader: View", "Sidebar group headers must be first-class disclosure controls")
        contains(sidebar, "static let disclosureGroupSpacing: CGFloat = 5", "Collapsed sidebar disclosure groups must use a compact list rhythm")
        contains(sidebar, "static let toolRowHorizontalPadding: CGFloat = 9", "Sidebar tool rows must keep a named base padding for selection rail alignment")
        contains(sidebar, "static let toolRowHierarchyIndent: CGFloat = 16", "Sidebar child tool rows must use a named hierarchy indent")
        contains(sidebarRenderer, "systemImage: group.systemImage", "Sidebar disclosure headers must include the projected category icon")
        contains(sidebar, "Image(systemName: \"chevron.right\")", "Sidebar disclosure headers must use a stable chevron glyph")
        contains(sidebar, ".rotationEffect(.degrees(isExpanded ? 90 : 0))", "Sidebar disclosure state must be shown through chevron rotation instead of glyph swapping")
        contains(sidebar, ".padding(.leading, SidebarMetrics.toolRowHorizontalPadding + SidebarMetrics.toolRowHierarchyIndent)", "Sidebar child row content must indent under the group title without shrinking the row background")
        contains(sidebar, ".padding(.trailing, SidebarMetrics.toolRowHorizontalPadding)", "Sidebar child row trailing padding must keep the existing row action affordance space")
        contains(sidebar, ".offset(x: -SidebarMetrics.toolRowHorizontalPadding)", "Sidebar selection rail must stay aligned to the full row background, not the indented content")
        contains(sidebar, ".accessibilityValue(shouldHighlight ? \"已选择\" : \"\")", "Sidebar tool rows must expose the selected state to accessibility")
        contains(sidebar, "SidebarNavigationEntryProjection.entries(", "Sidebar disclosure state must project into one tested flat identity domain")
        contains(sidebar, "SidebarNavigationList(configuration:", "Sidebar headers and tools must render through one stable flat identity domain")
        doesNotContain(sidebar, "ForEach(sidebarEntries)", "Sidebar disclosure must not structurally insert and remove SwiftUI rows")
        contains(sidebar, "static let interRowSpacing: CGFloat = 1", "Flat sidebar tool rows must preserve the existing one-point row rhythm through an independent track")
        doesNotContain(sidebar, "ToolDisclosureBody(", "Cross-group tool moves must not be split across clipped per-group disclosure bodies")
        doesNotContain(sidebar, ".frame(height: isExpanded ? nil : 0, alignment: .top)", "Sidebar disclosure rows must not collapse by compressing their real content")
        contains(sidebar, ".accessibilityValue(isExpanded ? \"已展开\" : \"已收起\")", "Disclosure headers must expose expanded/collapsed accessibility state")
        contains(sidebar, "if hoverState.isHovered {\n            return ToolTheme.hoverFill", "Sidebar disclosure headers may show hover fill but must not inherit child selection fill")
        doesNotContain(sidebar, ".move(edge: .top)", "Sidebar disclosure content must not fly in or out from the top")
        doesNotContain(sidebar, ".textCase(.uppercase)", "Sidebar category labels must preserve Chinese labels and normal Web casing")
        doesNotContain(sidebar, ".tracking(0.8)", "Sidebar category labels must not use caption-style letter spacing")
        doesNotContain(sidebar, "isActive: isActive", "Sidebar disclosure headers must not inherit selected child section state")
        doesNotContain(sidebar, "let isActive = projection.selectedSection == group.section", "Sidebar group headers must not turn selected child ownership into parent-row selection")
        contains(sidebarRenderer, "onSelectTool(item.id)", "Selecting a row tool must call the shared navigation action path")
        contains(sidebarRenderer, "onToggleFavorite(item.id)", "Sidebar favorite toggles must call the shared navigation action path")
        contains(sidebar, ".accessibilityIdentifier(\"sidebar.favorite.\\(toolID.rawValue)\")", "Sidebar favorite controls must keep stable ToolID-scoped accessibility identity")
        doesNotContain(sidebar, "sidebarSections.expand(item.section.groupID)", "Sidebar must not duplicate section expansion rules")
        doesNotContain(sidebar, "private func toggleFavorite(for item: ToolNavigationItem)", "Sidebar must not duplicate favorite migration rules")

        contains(actions, "func selectTool(_ toolID: ToolID, dismissCommandPalette: Bool = false) -> Bool", "Navigation actions must own tool selection")
        contains(actions, "func toggleFavorite(_ toolID: ToolID) -> Bool?", "Navigation actions must own favorite migration")
        contains(actions, "sidebarSections.expand(section.groupID)", "Navigation actions must expand the section that owns the tool")
        contains(actions, "private func section(for toolID: ToolID) -> ToolNavigationSection?", "Navigation actions must centralize tool-to-section resolution")

        contains(disclosureStore, "class PersistentDisclosureExpansionStore: ObservableObject", "Sidebar section state must reuse the shared disclosure persistence owner")
        contains(store, "final class SidebarSectionExpansionStore: PersistentDisclosureExpansionStore", "Sidebar section expansion must keep its named shell store on top of the shared persistence owner")
        contains(store, "static let storageKey = \"tools.sidebar.collapsedSections.v1\"", "Sidebar section state must persist under a versioned shell preference key")
        contains(disclosureStore, "@Published private(set) var collapsedGroupIDs: Set<String>", "Store must persist collapsed ids so new sections default to visible")
        contains(disclosureStore, "defaults.set(collapsedGroupIDs.sorted(), forKey: storageKey)", "Collapsed section ids must be persisted in stable order")
    }
}
