import Foundation
import AppKit
@testable import XTools
import Testing

struct QueryListAndUtilitySourceContractTests {
    @Test func queryListPagesKeepInternalScrollWithoutWrappingEmptyResults() throws {
        let deviceInfo = try readSource("Sources/XTools/ToolPages/Utility/DeviceInformationPage.swift")
        let httpStatus = try readSource("Sources/XTools/ToolPages/Web/HTTPStatusCodesPage.swift")
        let timezone = try readSource("Sources/XTools/ToolPages/Time/TimezoneViewerPage.swift")
        let emoji = try readSource("Sources/XTools/ToolPages/Utility/EmojiPickerPage.swift")
        let emojiCollection = try readSource("Sources/XTools/ToolPages/Utility/EmojiCollectionView.swift")

        contains(deviceInfo, "workspaceSemantic: .queryListWorkspace", "Device information must use the query-list page shell")
        contains(deviceInfo, "IndexPanel(\"macOS 设备信息\") {\n                ScrollView {\n                    IndexKV(rows: rows, emptyText: \"加载设备信息中…\", copyable: true)", "Device information must keep its fixed information list in a panel-local scroll view")
        contains(deviceInfo, ".verticallyFilling()", "Device information query/list panel must fill the available workspace")

        contains(httpStatus, "IndexPanel(\"状态码（\\(filtered.count)）\") {\n                if filtered.isEmpty {\n                    emptyState\n                } else {\n                    List(filtered) { row in", "HTTP status must keep empty results outside its native list and render non-empty results through the internal list owner")
        contains(httpStatus, ".listStyle(.plain)", "HTTP status must use the native plain list virtualization path")
        contains(httpStatus, ".scrollContentBackground(.hidden)", "HTTP status native list must preserve the panel visual surface")
        doesNotContain(httpStatus, "LazyVStack(spacing: 0)", "HTTP status must not eagerly materialize every status row through the nested lazy stack path")
        contains(httpStatus, ".verticallyFilling()", "HTTP status query/list panel must fill the available workspace")

        contains(timezone, "IndexPanel(\"时区列表\") {\n                ScrollView {\n                    VStack(spacing: ToolMetrics.Spacing.lg)", "Timezone viewer must keep its browsable timezone list in a panel-local scroll view")
        contains(timezone, ".frame(maxWidth: .infinity, maxHeight: .infinity)", "Timezone internal list scroll view must fill the result panel")
        contains(timezone, ".verticallyFilling()", "Timezone query/list panel must fill the available workspace")

        contains(emoji, "if entries.isEmpty {\n            IndexEmptyState(", "Emoji empty search results must render the shared empty state before the collection renderer")
        contains(emoji, "} else {\n            IndexEmojiCollectionView(", "Emoji non-empty browse/search results must use the panel-local native collection renderer")
        contains(emoji, "private func specialSymbolSections(_ sections: [EmojiSection]) -> some View", "Emoji special-symbol browse mode must render catalog-owned sections")
        contains(emojiCollection, "static func sectioned(sections: [EmojiSection]", "Emoji special-symbol browse mode must project catalog sections into native collection sections")
        contains(emojiCollection, "groupTitle: subsectionIndex == 0 ? section.name : nil", "Emoji section projection must retain parent section headings")
        doesNotContain(emoji, "ToolDisclosureBody", "Emoji special-symbol browse mode must not add collapsible section state for the MVP")
        contains(emoji, ".verticallyFilling()", "Emoji query/list panel must fill the available workspace")

        for page in [deviceInfo, httpStatus, timezone, emoji] {
            doesNotContain(page, "IndexWorkspaceResultSurface(workspaceSemantic: .naturalHeightShortResultPanel)", "Query/list workspaces must not be reclassified as natural-height short result panels")
            doesNotContain(page, "IndexShortResultKV(", "Query/list workspaces must not reuse short-result KV semantics")
            doesNotContain(page, "IndexShortResultCardList(", "Query/list workspaces must not reuse short-result card semantics")
        }
    }

    @Test func deviceInformationKeepsOnlyUsefulDebugRowsAndCopyActions() throws {
        let page = try readSource("Sources/XTools/ToolPages/Utility/DeviceInformationPage.swift")
        let query = try readSource("Sources/XTools/ToolPages/Utility/DeviceInformationQuery.swift")
        let collector = try readSource("Sources/XTools/ToolPages/Utility/MacDeviceInformationCollector.swift")
        let session = try readSource("Sources/XTools/ToolPages/Utility/DeviceInformationSession.swift")
        let implementation = [page, query, collector, session].joined(separator: "\n")

        contains(page, "IndexKV(rows: rows, emptyText: \"加载设备信息中…\", copyable: true)", "Device information rows must expose per-row copy actions")
        contains(page, "@StateObject private var session = DeviceInformationSession()", "Device information page must hold one refreshable query session")
        contains(page, "DeviceInformationProjection.fields(from: session.snapshot)", "Device information page must render the pure snapshot projection")
        contains(page, "NSApplication.didChangeScreenParametersNotification", "Device information must refresh when the display configuration changes")
        contains(page, "session.refresh()", "Device information screen-change wiring must refresh the query session")
        doesNotContain(page, "NSScreen.main", "Device information page must not label the keyboard-focus screen as the primary display")
        doesNotContain(page, "NSScreen.screens", "Device information page must render a captured display snapshot")
        doesNotContain(page, "CGDisplay", "Device information page must not own CoreGraphics display projection")
        doesNotContain(page, "sysctlbyname", "Device information page must not own platform C queries")
        doesNotContain(page, "ProcessInfo.processInfo", "Device information page must render a snapshot instead of collecting process facts")
        doesNotContain(page, "DeviceInspector", "Device information page must not own network collection")

        contains(collector, "let screens = NSScreen.screens", "Device information collector must capture one consistent display array")
        contains(query, "snapshot.displays.first?.pixelSize", "Device information must derive the primary summary from the first display in the captured screen order")
        doesNotContain(query, "primaryDisplayPixelSize", "Device information snapshot must not duplicate primary display pixels outside the ordered display collection")
        doesNotContain(collector, "NSScreen.main", "Device information collector must not use the keyboard-focus screen as the primary display")
        contains(collector, "localNetworkAddress(family: .ipv4)", "Device information must let the core selector choose the best local IPv4 interface")
        contains(query, "\"本机 IPv4\"", "Device information projection must expose one local IPv4 debug row")
        contains(query, "DeviceInfoFormatter.formatLocalNetworkAddress", "Device information must format network addresses through the Core formatter")
        doesNotContain(query, "import SwiftUI", "Device information snapshot and projection must stay UI-neutral")
        doesNotContain(query, "import AppKit", "Device information snapshot and projection must not expose platform UI types")
        contains(session, "@Published private(set) var snapshot: DeviceInformationSnapshot", "Device information session must expose a read-only snapshot")
        contains(session, "func refresh()", "Device information session must expose one explicit refresh command")

        doesNotContain(implementation, "\"活跃核心\"", "Device information must not include active-core noise")
        doesNotContain(implementation, "\"温控状态\"", "Device information must not include thermal-state noise")
        doesNotContain(implementation, "thermalStateName(", "Device information must not keep unused thermal-state formatting")
        doesNotContain(implementation, "localNetworkAddress(interfaceName: \"en0\", family: .ipv4)", "Device information must not hard-code en0")
        doesNotContain(implementation, "localNetworkRows", "Device information must not list every local network interface")

        doesNotContain(implementation, "\"降低动态效果\"", "Device information must not include accessibility preference noise")
        doesNotContain(implementation, "\"降低透明度\"", "Device information must not include accessibility preference noise")
        doesNotContain(implementation, "\"增强对比度\"", "Device information must not include accessibility preference noise")
        doesNotContain(implementation, "\"低电量模式\"", "Device information must not include low-power mode")
        doesNotContain(implementation, "\"App 版本\"", "Device information must not include app version")
        doesNotContain(implementation, "\"Bundle ID\"", "Device information must not include bundle id")
        doesNotContain(implementation, "\"缩放因子\"", "Device information must not include standalone scale factor")
        doesNotContain(implementation, "\"外观\"", "Device information must not include appearance")
        doesNotContain(implementation, "\"进程 ID\"", "Device information must not include process id")
        doesNotContain(implementation, "\"Darwin 内核\"", "Device information must not include Darwin kernel")
        doesNotContain(implementation, "\"语言\"", "Device information must not include language")
        doesNotContain(implementation, "\"日历\"", "Device information must not include calendar")
        doesNotContain(implementation, "\"主屏幕逻辑尺寸\"", "Device information must not include logical screen size")
        doesNotContain(implementation, "\"可用区域\"", "Device information must not include visible frame")
        doesNotContain(implementation, "\"色彩空间\"", "Device information must not include color space")
    }

    @Test func utilityPagesDelegateToCoreLogicAndBoundRendering() throws {
        let math = try readSource("Sources/XTools/ToolPages/Utility/MathEvaluatorPage.swift")
        let textStats = try readSource("Sources/XTools/ToolPages/Utility/TextStatisticsPage.swift")
        let textStatsModel = try readSource("Sources/XTools/ToolPages/Utility/TextStatisticsWorkspaceModel.swift")
        let emoji = try readSource("Sources/XTools/ToolPages/Utility/EmojiPickerPage.swift")
        let emojiCollection = try readSource("Sources/XTools/ToolPages/Utility/EmojiCollectionView.swift")
        let fileType = try readSource("Sources/XTools/ToolPages/Utility/FileTypeDetectorPage.swift")
        let fileTypeSession = try readSource("Sources/XTools/ToolPages/Utility/FileTypeDetectorSession.swift")

        contains(math, "MathExpressionEvaluator.evaluateLiveInput(trimmed)", "Math page must delegate live expression classification to Core")
        contains(math, ".indexWorkspaceDiagnostic(diagnosticText)", "Math page diagnostics must use the shared non-displacing workspace anchor")
        doesNotContain(math, "mathDiagnosticAccessory", "Math page must not hand-build title-accessory diagnostics that squeeze the header")
        doesNotContain(math, "ToolFeedbackTone.error.systemImage", "Math page must not hand-build persistent error labels")
        doesNotContain(math, ".accessibilityLabel(\"错误：", "Math page must rely on the shared diagnostic accessibility label")
        doesNotContain(math, "mathFeedbackSlot", "Math page must not reserve body space for live validation feedback")
        doesNotContain(math, ".frame(maxWidth: .infinity, minHeight: 50, alignment: .topTrailing)", "Math page must not keep a large empty feedback slot below the input")
        doesNotContain(math, "NSExpression", "Math page must not evaluate expressions through Foundation's dynamic expression engine")
        doesNotContain(math, "JavaScriptCore", "Math page must not evaluate expressions through a script engine")

        doesNotContain(textStats, "TextStatistics.analyze(", "Text statistics View body must not run Unicode-aware analysis on the main actor")
        contains(textStatsModel, "TextStatistics.analyze(input, shouldCancel: shouldCancel)", "Text statistics background model must delegate cancellable Unicode-aware counting to Core")
        contains(textStatsModel, "SupersedingExecutionSession(cancelInFlight: true)", "Text statistics analysis must use the shared serial latest-wins worker")
        contains(textStats, "workspaceSemantic: .fixedInputWorkspace", "Text statistics must preserve the fixed-input workspace semantic")
        contains(textStats, "TextStatisticsAnalysisStatus(isAnalyzing: workspace.isAnalyzing)", "Text statistics must expose analysis state in the statistics panel header")
        contains(textStats, "valueMotion: .immediate", "Text statistics values must remain immediate rather than animating each completion")
        doesNotContain(textStats, "IndexProgressMotionLabel", "Text statistics loading feedback must not add animated text or icon swaps")

        contains(fileTypeSession, "FileTypeDetector.inspect(", "File type session must delegate evidence resolution, size, and header interpretation to Core")
        contains(fileTypeSession, "read(upToCount: maxByteCount)", "File type reader must keep file reads bounded to the detector prefix limit supplied by the session")
        contains(fileTypeSession, "maxByteCount: FileTypeDetector.leadingByteLimit", "File type session must request only the Core detector prefix limit")
        doesNotContain(fileType, "FileTypeDetector.inspect(", "File type page must leave report construction in the session")
        doesNotContain(fileType, "FileHandle(forReadingFrom:", "File type page must not read selected files on the main actor")

        contains(emoji, "\"Emoji 与符号\"", "Emoji page title must reflect that it now includes symbols")
        contains(emoji, "EmojiCatalog.specialSymbolCount", "Emoji page subtitle must count unique special symbols separately")
        contains(emoji, "private static let displayLimit = 200", "Emoji page must cap broad search rendering for predictable grid performance")
        contains(emoji, "EmojiCatalog.search(matching: query, limit: Self.displayLimit)", "Emoji search must use Core's structured capped result")
        contains(emojiCollection, "EmojiCatalog.apply(tone: tone, to: entry)", "Emoji renderer must delegate skin-tone application to Core")
        contains(emoji, "var showsSkinToneControl: Bool", "Emoji tone visibility must be explicit result capability state")
        contains(emoji, "entries.contains(where: \\.skinToneCapable)", "Emoji tone visibility must follow current result capability rather than a category-name whitelist")
        let emojiActionBar = sourceSlice(emoji, from: "IndexActionBar {", to: "if !display.isSearching")
        doesNotContain(emojiActionBar, "skinToneControl", "The global search bar must not retain a tone control that appears valid for every category")
        doesNotContain(emojiActionBar, "autoFocus: true", "Emoji search must wait for an explicit click instead of blinking the caret on page entry")
        let emojiPanel = sourceSlice(emoji, from: "IndexPanel(display.panelTitle)", to: ".verticallyFilling()")
        contains(emojiPanel, "panelAccessory(for: display)", "The result panel header must own its contextual accessory")
        let emojiPanelAccessory = sourceSlice(emoji, from: "private func panelAccessory(for display: DisplayState)", to: "private func emojiGrid")
        contains(emojiPanelAccessory, "if display.isTruncated", "The result panel header must disclose capped search results")
        contains(emojiPanelAccessory, "仅展示前 200 个结果", "The result panel header must state the visible search limit")
        contains(emojiPanelAccessory, "if display.showsSkinToneControl", "The result panel header must reveal tone options only for capable results")
        contains(emojiPanelAccessory, "skinToneControl", "The result panel header must own the tone selector")
        contains(emoji, "density: .compact", "The six-option Emoji tone selector must use the compact shared segmented-control density")
        contains(emojiCollection, "helpText: entry.helpText(for: glyph)", "Emoji native cells must retain exact rendered-glyph help text")
    }

    @Test func customLiveValidationPagesSurfaceInvalidInputThroughWorkspaceDiagnostics() throws {
        let math = try readSource("Sources/XTools/ToolPages/Utility/MathEvaluatorPage.swift")
        let color = try readSource("Sources/XTools/ToolPages/Image/ColorPickerPage.swift")
        let userAgent = try readSource("Sources/XTools/ToolPages/Web/UserAgentParserPage.swift")
        let basicAuth = try readSource("Sources/XTools/ToolPages/Web/BasicAuthGeneratorPage.swift")

        contains(math, "MathExpressionEvaluator.evaluateLiveInput(trimmed)", "Math live validation must stay in Core")
        contains(math, ".indexWorkspaceDiagnostic(diagnosticText)", "Math invalid-expression diagnostics must use the non-displacing workspace anchor")

        contains(color, "@Published private(set) var state = CSSColorWorkspaceState()", "Color page must retain one canonical draft/result snapshot")
        contains(color, "CSSColorWorkspaceReducer.reduce(state: &next, action: action)", "Color page must route every edit through the Core reducer")
        contains(color, ".indexWorkspaceDiagnostic(workspace.state.diagnostic?.message)", "Color diagnostics must use the non-displacing workspace anchor")
        contains(color, "IndexTextInput(", "Color page must keep a directly editable general CSS color input")
        contains(color, "CSS 颜色", "Color page input must expose a truthful accessibility label")
        doesNotContain(color, "autoFocus: true", "Color page must not trigger AppKit autofocus during tool entry")
        contains(color, "@State private var showsSystemColorPicker = false", "Color page must keep system ColorPicker behind an explicit on-demand state")
        contains(color, ".popover(isPresented: $showsSystemColorPicker", "Color page must mount the system ColorPicker only when the picker popover is requested")
        contains(color, "private var systemColorPicker: some View", "Color page must keep the deferred system ColorPicker in a named helper")
        let pickerBody = sourceSlice(color, from: "private var pickerBody: some View", to: "private var systemColorPicker: some View")
        doesNotContain(pickerBody, "ColorPicker(", "Color page first paint must not directly mount the system ColorPicker inside pickerBody")
        let systemColorPicker = sourceSlice(color, from: "private var systemColorPicker: some View", to: "private func hslBinding")
        contains(systemColorPicker, "ColorPicker(", "Color page must preserve system ColorPicker capability inside the on-demand helper")
        contains(systemColorPicker, "supportsOpacity: true", "System color picking must preserve Alpha")
        contains(color, "IndexDisclosure(", "Advanced color spaces must stay bounded behind the shared disclosure component")
        doesNotContain(color, "DisclosureGroup(", "Color disclosure must not regress to the arrow-only system hit target")
        contains(color, "IndexBadge(\"映射到 sRGB\", tone: .warning)", "Legacy display formats must visibly disclose gamut mapping through the shared warning badge")
        contains(color, "title: \"复制 \\(value.label)\"", "Every color result must expose a format-specific copy label")
        contains(color, "accessibilityName: \"Alpha 透明度\"", "Alpha must remain keyboard and VoiceOver adjustable")
        doesNotContain(color, "suppressNextHexSync", "The canonical reducer must not retain the old one-shot feedback-loop flag")

        contains(userAgent, "UserAgentParser.validationIssue(trimmed)", "UserAgent page must distinguish empty input from structurally invalid input")
        contains(userAgent, "error = userAgentErrorMessage(for: UserAgentParser.validationIssue(trimmed))", "UserAgent page must surface structurally invalid strings instead of silently clearing results")
        contains(userAgent, ".indexWorkspaceDiagnostic(workspace.error)", "UserAgent retained errors must use the non-displacing workspace anchor")
        occurrenceCount(userAgent, ".indexWorkspaceDiagnostic(workspace.error)", 1, "UserAgent must expose one retained input-owned error diagnostic")
        appearsBefore(userAgent, ".indexWorkspaceDiagnostic(workspace.error)", "IndexPanel(\"解析结果\")", "UserAgent errors must belong to the input panel rather than the result panel")

        let basicAuthSession = try readSource("Sources/XToolsCore/Web/BasicAuthWorkspaceSession.swift")
        contains(basicAuthSession, "public var outputDiagnostic: String?", "Basic Auth must promote invalid credential states to a persistent diagnostic in the Core session")
        contains(basicAuth, ".indexWorkspaceDiagnostic(session.outputDiagnostic)", "Basic Auth invalid credentials must use the non-displacing workspace anchor")
    }

    @Test func regexTesterMapsErrorsAndUsesCompactFlagMenu() throws {
        let page = try readSource("Sources/XTools/ToolPages/Development/RegexTesterPage.swift")
        let components = try readSource("Sources/XTools/ToolPages/Development/RegexTesterComponents.swift")
        let executionSession = try readSource("Sources/XTools/ToolPages/Development/RegexExecutionSession.swift")

        contains(page, "private var flagMenu: some View", "Regex tester must keep supported flags in one compact, width-stable control")
        contains(page, "Toggle(\"全局匹配 (g)\", isOn: flagBinding(\"g\"))", "Regex tester flag menu must expose the global match option")
        contains(page, "Toggle(\"允许注释与空白 (x)\", isOn: flagBinding(\"x\"))", "Regex tester flag menu must expose the supported x option")
        contains(page, "Text(activeFlagsLabel)", "Regex tester flag menu must show only the active flags without a redundant prefix")
        doesNotContain(page, #"Text("flags: \(activeFlagsLabel)")"#, "Regex tester must not repeat the flags label inside the /pattern/flags expression row")
        contains(page, "private var activePresetTitle: String", "Regex tester must derive a truthful current preset title")
        contains(page, ".toolMotionTextSwap(id: activePresetTitle)", "Regex tester must swap the compact preset title inside a stable control")
        occurrenceCount(page, ".menuIndicator(.hidden)", 2, "Regex tester must hide both detached system menu indicators")
        contains(page, #"Image(systemName: "chevron.down")"#, "Regex tester compact menus must own their chevrons inside the shared button surface")
        doesNotContain(page, "showsAdvancedFlags", "Regex tester must not keep a second raw-flag editing surface for the same five supported flags")
        doesNotContain(page, "IndexOptionSwitch(", "Regex tester must not lay out variable-width flag switches that scramble at narrow widths")
        contains(page, "Menu {", "Regex tester presets must use a compact native action menu in the panel header")
        doesNotContain(page, "IndexOptionMenu(", "Regex tester must not place the 38-point option selector inside the 34-point panel header")
        contains(page, ".onChange(of: workspaceInput)", "Regex tester must schedule one coordinated snapshot instead of three independent field observers")
        doesNotContain(page, ".onChange(of: workspace.pattern)", "Regex preset application must not fan out through a pattern-only observer")
        doesNotContain(page, ".onChange(of: workspace.flags)", "Regex preset application must not fan out through a flags-only observer")
        doesNotContain(page, ".onChange(of: workspace.text)", "Regex preset application must not fan out through a text-only observer")
        contains(page, "let execution = RegexExecutionSession()", "Regex tester must delegate matching state to the asynchronous execution session")
        contains(executionSession, "workGate.runDetached", "Regex tester must execute ICU matching through the shared detached work gate")
        contains(try readSource("Sources/XToolsCore/Utility/AsyncWorkGate.swift"), "Task.detached(priority: .userInitiated)", "AsyncWorkGate.runDetached must leave the main actor for ICU/regex work")
        contains(executionSession, "catch let error as RegexMatcher.MatcherError", "Regex execution session must catch matcher errors explicitly")
        contains(executionSession, "self.error = error.errorDescription ?? \"正则匹配失败。\"", "Regex execution session must surface normalized matcher diagnostics without raw library text")
        doesNotContain(executionSession, "localizedDescription", "Regex tester must not surface raw matcher localizedDescription text")
        doesNotContain(page, "error = \"无效的正则表达式\"", "Regex tester must not collapse all matcher errors into the old generic message")
        contains(page, "execution.invalidate()\n        guard !workspace.pattern.isEmpty else {", "Regex tester must clear execution state before handling empty patterns")
        contains(executionSession, "report = nil", "Regex execution session invalidation must clear stale output")
        contains(executionSession, "reportSourceText = nil", "Regex execution session invalidation must clear the source snapshot used for temporary highlights")
        contains(executionSession, "error = nil", "Regex execution session invalidation must clear stale diagnostics")
        contains(page, "let debouncer = IndexDebouncer()", "Regex tester must keep debounced matching for large input")
        contains(page, "debouncer.schedule {\n            execution.run(pattern: patternSnapshot, text: textSnapshot, flags: flagsSnapshot)", "Regex tester must schedule snapshot analysis through the debouncer")
        contains(page, "RegexMatcher.summaryText(for: report)", "Regex tester copied summary must include captures and named groups through the tested formatter")
        doesNotContain(page, "替换", "Regex tester P0 must not add replace UI")
        doesNotContain(page, "Replace", "Regex tester P0 must not add replace UI")
        doesNotContain(components, "替换", "Regex tester components P0 must not add replace UI")
        doesNotContain(components, "Replace", "Regex tester components P0 must not add replace UI")
    }

    @Test func sharedSwitchesUseNativeToggleSemantics() throws {
        let controls = try readSource("Sources/XTools/ToolPages/Workbench/Controls/IndexControls.swift")
        let switchSurface = sourceSlice(
            controls,
            from: "struct IndexSwitch: View",
            to: "struct IndexSwitchToggleStyle: ToggleStyle"
        )
        let optionSwitchSurface = sourceSlice(
            controls,
            from: "struct IndexOptionSwitch: View",
            to: "private struct IndexOptionSwitchToggleStyle: ToggleStyle"
        )

        contains(switchSurface, "Toggle(isOn: $isOn)", "IndexSwitch must expose native toggle role and state semantics")
        contains(optionSwitchSurface, "Toggle(isOn: $isOn)", "IndexOptionSwitch must expose native toggle role and state semantics")
        contains(controls, "struct IndexSwitchToggleStyle: ToggleStyle", "IndexSwitch must preserve the app visual language through a custom ToggleStyle")
        contains(controls, ".accessibilityValue(isOn ? \"已开启\" : \"已关闭\")", "Shared switches must announce their current state")
        doesNotContain(switchSurface, "Button { isOn.toggle() }", "IndexSwitch must not impersonate toggle behavior with a plain button")
    }

    @Test func regexResultWorkspaceExpandsNaturallyWithoutInternalScroll() throws {
        let page = try readSource("Sources/XTools/ToolPages/Development/RegexTesterPage.swift")
        let components = try readSource("Sources/XTools/ToolPages/Development/RegexTesterComponents.swift")
        let sharedComponents = try readSharedBagComponents()

        contains(page, "\"正则测试\"", "Regex tester must keep its page identity")
        contains(page, "workspaceSemantic: .regexResultWorkspace", "Regex tester must name the page-level natural-height workspace semantic")
        occurrenceCount(page, "IndexPanel(", 2, "Regex tester must keep only the pattern and test-text panels")
        doesNotContain(page, "IndexPanel(\"匹配结果\")", "Regex tester must not repeat the whole test text in a third result panel")
        contains(page, "minHeight: 56", "Regex test text must start at a compact two-line floor and grow naturally with content")
        contains(page, "temporaryHighlights: temporaryHighlights", "Regex matches must be rendered directly in the editable test text")
        contains(page, "execution.reportSourceText", "Regex highlights must use the exact text snapshot that produced the report")
        contains(page, "sourceText == workspace.text", "Regex must hide a report as soon as the editable text no longer matches its execution snapshot")
        contains(page, "report.pattern == workspace.pattern", "Regex must hide a report as soon as the pattern changes")
        contains(page, "report.flags == workspace.flags", "Regex must hide a report as soon as the active flags change")
        contains(page, "IndexTextAreaCharacterRangeProjection.utf16Ranges", "Regex Character offsets must be projected to AppKit UTF-16 ranges")
        contains(page, "RegexResultStatus(", "Regex execution state must remain visible below the editable test text")
        contains(page, "RegexResultSummary(stats: stats(for: report))", "Regex statistics must stay below the editable test text")
        contains(page, "if !report.matches.isEmpty", "Regex result workspace must omit redundant empty match-detail cards")
        contains(page, "RegexMatchList(matches: report.matches, valueMotion: .immediate)", "Regex match details must remain grouped and update without high-frequency animation")
        contains(page, "IndexCopyButton(text: resultText, title: \"复制匹配结果\")", "Regex must retain an explicitly named structured-result copy action")
        contains(page, "输入正则表达式后显示匹配。", "Regex must distinguish an empty pattern")
        contains(page, "正在更新匹配…", "Regex must distinguish pending and running work")
        contains(page, "请修正上方正则表达式。", "Regex must keep the test panel actionable while the pattern diagnostic stays above")
        contains(page, "未找到匹配。", "Regex must distinguish a valid expression with no matches")
        doesNotContain(page, "RegexHighlightedPreview", "Regex must not retain a second read-only copy of the test text")
        doesNotContain(page, "IndexWorkspaceResultSurface", "Regex feedback must stay in the test-text panel rather than a detached result surface")
        doesNotContain(page, "IndexStatGrid(", "Regex result workspace must not reserve the tall generic statistics grid")
        doesNotContain(page, ".animation(", "Regex high-frequency updates must not add page-local animation")
        doesNotContain(page, ".transition(", "Regex high-frequency updates must not add page-local transitions")
        appearsBefore(page, "temporaryHighlights: temporaryHighlights", "RegexResultStatus(", "Editable match highlighting must stay before status and details")
        appearsBefore(page, "RegexResultStatus(", "RegexResultSummary(stats: stats(for: report))", "Regex status must stay before compact statistics")
        appearsBefore(page, "RegexResultSummary(stats: stats(for: report))", "RegexMatchList(matches: report.matches, valueMotion: .immediate)", "Regex summary must stay before grouped match details")

        contains(components, "struct RegexResultStatus: View", "Regex state messaging must live in a named compact component")
        contains(components, ".font(ToolTypography.compactBody)", "Regex state messaging must use the centralized compact readable token")
        contains(components, "struct RegexResultSummary: View", "Regex result metrics must live in a named compact component")
        contains(components, "ViewThatFits(in: .horizontal)", "Regex result metrics must switch to a deliberate narrow-width fallback instead of wrapping unpredictably")
        doesNotContain(components, "struct RegexHighlightedPreview", "Regex components must not preserve the duplicate full-text preview")
        doesNotContain(components, "ScrollView {", "Regex details must rely on the page scroll owner")
        doesNotContain(components, "let emptyText", "Regex match details must not render a second empty-state result card")
        contains(components, "LazyVStack(spacing: 8)", "Regex match details must use lazy grouped rendering")
        contains(components, "struct RegexMatchList: View", "Regex match details must be a named grouped result component")

        contains(sharedComponents, "var valueLineBreakMode: NSLineBreakMode? = .byCharWrapping", "Shared key-value rows must wrap long content values by default")
        contains(sharedComponents, "if let valueLineBreakMode", "Match detail rows must be able to opt into long-token wrapping")
        contains(sharedComponents, "Text(indexWrappingAttributedText(value, lineBreakMode: valueLineBreakMode))", "Match detail rows must use explicit long-token wrapping when requested")
        contains(sharedComponents, "Text(value)", "Shared key-value rows must preserve an explicit nil fallback for plain text rendering")
        contains(sharedComponents, ".fixedSize(horizontal: false, vertical: true)", "Match detail values must expand to natural row height")
    }

    @Test func jwtPageKeepsBidirectionalMixedWorkspaceSemantics() throws {
        let source = try readSource("Sources/XTools/ToolPages/Web/JWTParserPage.swift")
        let session = try readSource("Sources/XToolsCore/JWT/JWTWorkspaceSession.swift")
        let presentation = try readSource("Sources/XToolsCore/JWT/JWTLocalCheckPresentation.swift")
        let sharedComponents = try readSharedBagComponents()

        contains(source, "ToolWorkspaceHost(key: JWTToolWorkspaceModel.key)", "JWT page must resolve its retained per-tool workspace")
        contains(source, "@Binding var session: JWTWorkspaceSession", "JWT workspace content must keep binding the Core value session")
        contains(session, "mode: Mode = .parse", "JWT session must preserve parse as its initial mode")
        contains(source, "IndexGenerateParseModeBar(", "JWT must expose the shared generate/parse mode bar")
        contains(source, "IndexGenerateParseModeContent(mode: modeBinding.wrappedValue)", "JWT must render mode-specific structured workflows through the shared transition container")
        contains(source, "\"JWT\",", "JWT page title must use the bidirectional tool name")
        contains(source, "layout: .scroll", "JWT must retain page-level scrolling for its mixed workspace")
        doesNotContain(source, "IndexConverterPage(", "JWT must not be forced into the symmetric string converter shell")
        doesNotContain(source, "@AppStorage", "JWT must not persist token or secret drafts")
        doesNotContain(source, "@SceneStorage", "JWT must not persist token or secret drafts")

        contains(source, "IndexWorkspaceTextArea(", "JWT inputs must use workspace semantic text surfaces")
        contains(source, "workspaceSemantic: .longTextNaturalInput", "JWT inputs must use natural page-scrolled input behavior")
        contains(source, "IndexPairLayout(collapseWidth: 0) {", "JWT Header/Payload pairs must stay structured in narrow layouts")
        occurrenceCount(source, "IndexWorkspaceOutputSurface(", 4, "JWT generation and parsing must use semantic output surfaces")
        occurrenceCount(source, "workspaceSemantic: .structuredOutputReading", 4, "JWT long outputs must keep structured reading semantics")
        contains(source, "IndexWorkspaceResultSurface(workspaceSemantic: .naturalHeightShortResultPanel)", "JWT verification result must keep the natural-height short-result semantic")

        contains(source, "@State private var showsGenerateSecret = false", "JWT generation secret must start hidden")
        contains(source, "@State private var showsParseSecret = false", "JWT verification secret must start hidden")
        contains(source, "IndexSecureInput(", "JWT shared secret field must use the shared secure input")
        contains(source, "showsSecret: $showsGenerateSecret", "JWT generation secret must bind the shared reveal state")
        occurrenceCount(source, "IndexOptionLabel(\"密钥格式\")", 2, "JWT generate and parse modes must label secret representation explicitly")
        contains(source, "(JWTSecretEncoding.utf8.rawValue, \"普通文本\")", "JWT secret format must present the common UTF-8 path in user language")
        contains(source, "(JWTSecretEncoding.base64.rawValue, \"Base64\")", "JWT secret format must retain explicit Base64 key support")
        doesNotContain(source, "Secret 是 Base64 编码", "JWT must not expose secret representation as an ambiguous boolean sentence")
        contains(source, "private func secretEncodingHelp", "JWT secret format must explain when each representation applies")
        doesNotContain(source, "IndexPanel(\"高级 Header（可选）\")", "JWT generation must expose only one Header surface")
        doesNotContain(source, "placeholder: #\"例如 {\"kid\":\"key-1\",\"typ\":\"at+jwt\"}\"#", "JWT generation must not expose a free-form additional Header editor")
        contains(session, "generateAdditionalHeaderJSON: String = \"\"", "JWT must retain additional Header members only as compatibility state")
        occurrenceCount(session, "advancedHeaderJSON: generateAdditionalHeaderJSON", 2, "JWT preview and signing must preserve transferred additional Header members")
        contains(source, ".indexWorkspaceDiagnostic(session.generationHeaderError)", "The single Header preview must own Header diagnostics")
        contains(session, "public static let defaultGeneratePayload = \"\"\"", "JWT generation must define an editable Payload template in Core")
        contains(session, "generatePayload: String = JWTWorkspaceSession.defaultGeneratePayload", "JWT session must load the template into editable state")
        contains(session, "\"sub\": \"1234567890\"", "JWT default Payload must provide a common subject claim example")
        contains(session, "\"name\": \"John Doe\"", "JWT default Payload must provide a directly editable claim example")
        occurrenceCount(source, ".verticallyFilling()", 2, "JWT generation Header/Payload panels must accept the pair layout's equal height")
        occurrenceCount(source, "fillsHeight: true", 4, "JWT Header/Payload surfaces must visually fill their equal-height panels")
        contains(session, "JWTSigner.sign(config:", "JWT generation must delegate signing to Core codecs")
        contains(session, "JWTVerifier.verify(", "JWT verification must delegate to Core codecs")
        contains(presentation, "case .notVerified:", "JWT presentation must render the explicit not-verified state")
        contains(presentation, "public var localCheckPresentation: LocalCheckPresentation?", "JWT session must expose a typed local-check projection")
        contains(source, "在解析中检查", "JWT generated results must expose explicit local-check transfer")
        contains(source, "用于生成", "JWT parsed results must expose explicit generation transfer")
        contains(session, "public mutating func clearGenerate()", "JWT full reset must clear generate state in the session")
        contains(session, "public mutating func clearParse()", "JWT full reset must clear parse state in the session")
        contains(source, "private func clearAll()", "JWT must expose a full sensitive-state reset")
        contains(source, "session.clearAll()", "JWT page clear must delegate to the Core session")

        let parseBody = sourceSlice(source, from: "private var parseContent: some View", to: "private var parseSecretEncodingBinding")
        appearsBefore(parseBody, "IndexPanel(\"JWT\")", "IndexPanel(\"解码结果\")", "JWT parse input must stay before decoded content")
        appearsBefore(parseBody, "decodedHeaderPane", "decodedPayloadPane", "Decoded Header must stay before decoded Payload")
        appearsBefore(parseBody, "IndexPanel(\"解码结果\")", "localCheckDisclosure", "Decoded content must stay before the optional local-check disclosure")
        contains(source, "IndexDisclosure(", "JWT local check must use the shared disclosure component")
        doesNotContain(parseBody, "IndexPanel(\"本地检查配置（可选）\")", "Local-check configuration must not remain a separate panel")
        doesNotContain(parseBody, "IndexPanel(\"本地检查结果\")", "Local-check result must not remain a separate panel")
        doesNotContain(source, "验证通过", "JWT page must not claim application-level validity")
        doesNotContain(source, "验证失败", "JWT page must not claim application-level validity")

        contains(sharedComponents, "struct IndexWorkspaceResultSurface", "Short result panels must have a semantic result surface")
        contains(sharedComponents, "workspaceSemantic: IndexWorkspaceSemantic = .naturalHeightShortResultPanel", "Short result surface must default to the natural-height short result semantic")
        contains(sharedComponents, "fixedSize(horizontal: false, vertical: behavior.usesNaturalHeightSurface)", "Short result surface must apply natural-height behavior without adding internal scrolling")
    }

    @Test func naturalHeightShortResultEntrypointsStaySeparateFromScrollableLists() throws {
        let sharedComponents = try readSharedBagComponents()

        contains(sharedComponents, "struct IndexShortResultKV: View", "Shared UI must expose a natural-height KV entry for short results and file metadata")
        contains(sharedComponents, "var valueLineBreakMode: NSLineBreakMode = .byCharWrapping", "Short-result KV values must wrap long tokens by default")
        contains(sharedComponents, "var workspaceSemantic: IndexWorkspaceSemantic = .naturalHeightShortResultPanel", "Short-result entries must default to the natural-height short result semantic")
        contains(sharedComponents, "IndexWorkspaceResultSurface(workspaceSemantic: workspaceSemantic) {\n            IndexResultPresence(", "Short-result KV must keep presence inside the semantic natural-height surface")
        contains(sharedComponents, "value: rows.isEmpty ? nil : rows", "Short-result KV presence must follow only the empty/result boundary")
        contains(sharedComponents, "valueLineBreakMode: valueLineBreakMode", "Short-result KV must pass long-token wrapping into the underlying rows")

        contains(sharedComponents, "struct IndexShortResultCardList: View", "Shared UI must expose a natural-height result-card entry for bounded derived results")
        contains(sharedComponents, "IndexDerivedResultCardList", "Derived results must keep their semantic public entry")
        contains(sharedComponents, "IndexShortResultCardList(items: items, emptyText: emptyText)", "Derived results must route through the natural-height short result entry")
        contains(sharedComponents, "value: items.isEmpty ? nil : items", "Short result card presence must follow only the empty/result boundary")
        contains(sharedComponents, "IndexResultCardStack(items: snapshot, revealsItems: false)\n                    .padding(8)", "Short result card lists must preserve the existing card inset and use one structural motion owner")

        contains(sharedComponents, "struct IndexScrollableKV: View", "Scrollable KV must remain available for explicit query/list exceptions")

        contains(sharedComponents, "Text(indexWrappingAttributedText(item.value, lineBreakMode: .byCharWrapping))", "Result card values must wrap long tokens within the available card width")
        contains(sharedComponents, ".fixedSize(horizontal: false, vertical: true)", "Result card values must expand vertically instead of hiding wrapped lines")
        doesNotContain(sharedComponents, "if item.value.count > 240 {\n                    ScrollView {", "Result cards must not create a per-card scroller for long values")
    }

    @Test func shortResultPagesAvoidLockingLegacyInternalScrollContracts() throws {
        let textComponents = try readSource("Sources/XTools/ToolPages/Workbench/Text/IndexTextComponents.swift")
        let emptyStateComponents = try readSource("Sources/XTools/Shared/Components/IndexEmptyState.swift")
        let caseConverter = try readSource("Sources/XTools/ToolPages/Converter/CaseConverterPage.swift")
        let userAgent = try readSource("Sources/XTools/ToolPages/Web/UserAgentParserPage.swift")
        let hashText = try readSource("Sources/XTools/ToolPages/Crypto/HashTextPage.swift")
        let hashWorkspace = try readSource("Sources/XTools/ToolPages/Crypto/HashTextWorkspaceModel.swift")
        let base64File = try readSource("Sources/XTools/ToolPages/Converter/Base64FilePage.swift")
        let basicAuth = try readSource("Sources/XTools/ToolPages/Web/BasicAuthGeneratorPage.swift")

        contains(textComponents, "var lineBreakMode: NSLineBreakMode = .byCharWrapping", "Text areas must wrap long tokens by default while allowing explicit caller overrides")
        contains(textComponents, "textContainer.lineBreakMode = lineBreakMode", "Text areas must pass wrapping behavior to AppKit")
        contains(textComponents, "private func keepContentGrowingScrollOriginStable", "Content-growing text areas must keep their hidden internal clip view at the top")
        contains(textComponents, "guard growsWithContent else { return }", "Only content-growing text areas should reset the hidden internal scroll origin")

        contains(userAgent, "IndexPage(\"User-Agent 解析\", subtitle: \"本地尽力识别浏览器、操作系统与设备类型，仅供调试，不用于能力判断或安全决策。\", layout: .scroll)", "User-Agent parser must keep standard naming, its confidence boundary, and page-level scrolling")
        contains(userAgent, "IndexWorkspaceTextArea(", "UserAgent input must use a workspace semantic input surface")
        contains(userAgent, "workspaceSemantic: .longTextNaturalInput", "UserAgent input must grow with long content through the long-text semantic instead of hand-assembled flags")
        doesNotContain(userAgent, "IndexTextArea(", "UserAgent input must not bypass the workspace semantic input surface")
        doesNotContain(userAgent, "expandsWithContent: true", "UserAgent input must not hand-assemble natural growth outside the workspace semantic")
        doesNotContain(userAgent, "lineBreakMode: .byCharWrapping", "UserAgent input must not hand-assemble wrapping outside the workspace semantic")
        appearsBefore(userAgent, "IndexPanel(\"输入\")", "IndexPanel(\"解析结果\")", "UserAgent page must keep the input panel before the result panel")
        contains(userAgent, "IndexKVRow(key: \"浏览器\", value: result.browser, valueLineBreakMode: .byCharWrapping, valueMotion: .immediate)", "UserAgent result snapshots must keep the browser row")
        contains(userAgent, "IndexKVRow(key: \"操作系统\", value: result.os, valueLineBreakMode: .byCharWrapping, valueMotion: .immediate)", "UserAgent result snapshots must keep the OS row")
        contains(userAgent, "IndexWorkspaceResultSurface {", "UserAgent short result rows must use the natural-height result surface")
        contains(userAgent, "value: resultProjection", "UserAgent short results must pass a read-only projection into shared presence")
        contains(userAgent, "valueLineBreakMode: .byCharWrapping", "UserAgent result values must wrap long tokens within the available width")
        doesNotContain(userAgent, "ScrollView {", "UserAgent result rows must not create an internal scroll container")
        doesNotContain(userAgent, ".verticallyFilling()", "UserAgent result panel must not fill the viewport like a query/list workspace")

        contains(caseConverter, "IndexPage(\"大小写转换\", subtitle: \"在 camelCase、snake_case、kebab-case 等之间转换。\", workspaceSemantic: .longTextNaturalInput)", "Case converter must use the long-text semantic page shell")
        appearsBefore(caseConverter, "IndexPanel(\"输入\")", "IndexPanel(\"转换结果\")", "Case converter must keep the input panel before converted results")
        contains(caseConverter, "IndexWorkspaceTextArea(", "Case converter input must use a workspace semantic input surface")
        contains(caseConverter, "workspaceSemantic: .longTextNaturalInput", "Case converter input must select natural page-scrolled input behavior through the semantic seam")
        doesNotContain(caseConverter, "IndexTextArea(", "Case converter input must not bypass the workspace semantic input surface")
        contains(caseConverter, "CaseConversion.styles(workspace.text)", "Case converter must derive all case rows from the core helper")
        contains(caseConverter, "IndexClearButton(isDisabled: workspace.text.isEmpty)", "Case converter must keep the input-panel clear action")
        contains(caseConverter, "IndexShortResultKV(rows: rows, emptyText: IndexEmptyStateCopy.autoShow(\"文本\"), valueMotion: .immediate)", "Case converter results must use the natural-height short-result KV entry")
        doesNotContain(caseConverter, "IndexScrollableKV(rows: rows", "Case converter results must not create an internal scroll container")
        doesNotContain(caseConverter, ".verticallyFilling()", "Case converter result panel must not fill the viewport like a query/list workspace")
        contains(emptyStateComponents, #"输入\(source)后自动显示"#, "The auto-show empty copy used by short-result placeholders must stay canonical in the shared component")

        contains(hashText, "subtitle: \"计算 SHA-2、SHA-3、RIPEMD-160 摘要；SHA-1 与 MD5 仅用于兼容校验。\"", "Hash text must explain the compatibility-only algorithms without leading with them")
        contains(hashText, "workspaceSemantic: .boundedLongTextInput", "Hash text page must select the bounded long-text semantic for its page shell and input viewport")
        appearsBefore(hashText, "IndexActionBar {", "IndexPanel(\"输入\")", "Hash encoding selector must stay above the input panel")
        appearsBefore(hashText, "IndexPanel(\"输入\")", "IndexPanel(\"摘要结果\")", "Hash text page must keep the input panel before the digest results")
        contains(hashText, "IndexWorkspaceTextArea(", "Hash text input must use the shared semantic input surface")
        doesNotContain(hashText, "workspaceSemantic: .longTextNaturalInput", "Hash text input must not retain the unbounded natural-growth semantic")
        contains(hashText, "private var inputViewportHeight: CGFloat", "Hash text must keep a stable responsive input viewport independent of content length")
        contains(hashText, "min(148, max(104, pageAvailableHeight * 0.18))", "Hash text input viewport must stay useful at compact and large window heights without consuming the page")
        doesNotContain(hashText, "expandsWithContent: true", "Hash text input must not hand-assemble natural growth outside the workspace semantic")
        contains(hashText, "private var resultItems: [IndexResultCardItem]", "Hash digest results must keep named copyable result data")
        contains(hashText, "badgeText: item.isCompatibilityOnly ? \"仅兼容\" : nil", "Hash text must use typed compatibility metadata instead of page-level name checks")
        contains(hashText, "badgeTone: .warning", "Hash text compatibility digest badge must use the shared warning tone")
        contains(hashText, "workspace.computeExplicitly", "Large Hash input must expose a stable explicit calculation action")
        contains(hashWorkspace, "static let realtimeUTF8ByteLimit = 64 * 1_024", "Hash realtime policy must retain the benchmark-calibrated UTF-8 byte limit")
        let supersedingWorker = try readSource("Sources/XToolsCore/Utility/SupersedingDetachedWorker.swift")
        contains(hashWorkspace, "SupersedingExecutionSession(cancelInFlight: true)", "Hash workspace must use the shared superseding detached worker")
        contains(supersedingWorker, "private var pending: Request?", "Hash worker must coalesce to one latest pending request")
        contains(supersedingWorker, "activeToken?.cancel()", "Hash worker invalidation must cancel the active request at algorithm boundaries")
        contains(hashWorkspace, "HashDigestPipeline.compute(bytes, shouldCancel: shouldCancel)", "Hash workspace must delegate the eight-algorithm pipeline to Core")
        occurrenceCount(supersedingWorker, "Task.detached(priority: .userInitiated)", 1, "Hash worker must have one controlled detached execution site")
        doesNotContain(hashText, "import CryptoSwift", "Hash page must not import CryptoSwift after pipeline extraction")
        doesNotContain(hashWorkspace, "import CryptoSwift", "Hash workspace must not own digest implementations")
        let pipeline = try readSource("Sources/XToolsCore/Crypto/HashDigestPipeline.swift")
        contains(pipeline, "public enum HashDigestAlgorithm", "Core hash pipeline must expose typed algorithm descriptors")
        contains(pipeline, "case .sha1, .md5", "Core hash metadata must keep SHA-1 and MD5 as compatibility-only algorithms")
        contains(pipeline, "RIPEMD160.hash", "Core hash pipeline must keep RIPEMD-160")
        contains(pipeline, "Array(Insecure.MD5.hash", "Core hash pipeline must use the platform MD5 implementation")
        doesNotContain(pipeline, "Digest.md5", "Core hash pipeline must not keep common digests on the slower CryptoSwift path")
        contains(hashText, "IndexCopyButton(text: allDigestsText, title: \"全部复制\")", "Hash digest copy behavior must stay in the result panel header")
        contains(hashText, "IndexDerivedResultCardList(items: resultItems, emptyText: emptyResultText)", "Hash digest results must use the natural-height derived result card entry")
        doesNotContain(hashText, ".verticallyFilling()", "Hash digest result panel must not fill the viewport like a query/list workspace")

        occurrenceCount(base64File, "Base64DecodedMetadataList(", 1, "Base64 file page must keep one decoded short-result surface")
        contains(base64File, "Base64DecodedMetadataList(rows: metadataRows(projection.reverseRows))", "Base64 decoded metadata must use natural-height prototype-aligned rows")
        doesNotContain(base64File, "selectedFileRows", "Base64 selected-file metadata must stay inside the compact picker instead of a second result surface")
        doesNotContain(base64File, "IndexScrollableKV(rows: reverseRows", "Base64 decoded metadata must not create an internal scroll container")
        occurrenceCount(base64File, ".verticallyFilling()", 4, "Base64 file panels must accept the responsive workbench row height so wide columns align")
        contains(base64File, "text: session.outputPreview?.visibleText ?? \"\"", "Base64 encoded output must render the bounded preview surface")
        contains(base64File, "minHeight: Base64FileLayout.primaryContentMinHeight", "Base64 reverse pasted input must keep a stable bounded editor minimum")
        contains(base64File, "static let primaryContentMinHeight: CGFloat = 136", "Base64 primary surfaces must share the prototype's content minimum")
        contains(base64File, "minHeight: Base64FileLayout.primaryContentMinHeight,\n                    maxHeight: .infinity", "Base64 source-file picker must keep one stable identity while filling the complete pane body")
        contains(base64File, "static let minimumStackedPaneHeight: CGFloat = 280", "Base64 stacked panes must retain the approved compact complete-pane height")
        doesNotContain(base64File, "emptyFilePickerHeight", "Base64 empty state must not use a taller picker that shifts the workflow")
        doesNotContain(base64File, "selectedFilePickerHeight", "Base64 selected state must not use a second picker height")
        contains(base64File, "maxUTF8Bytes: Base64FileWorkflowSession.editableReverseInputByteLimit", "Base64 reverse pasted input must keep oversized text out of the editable AppKit path")
        contains(base64File, "Text(indexWrappingAttributedText(selectedFile.fileName, lineBreakMode: .byCharWrapping))\n                    .font(ToolTypography.bodyMedium)\n                    .foregroundStyle(ToolTheme.textPrimary)\n                    .lineLimit(nil)", "Base64 picker must wrap long selected filenames and present the file as the selected-state primary label")
        contains(base64File, "\"\\(ByteSizeFormatter.format(bytes: selectedFile.byteCount)) · \\(selectedFile.mimeType)\"", "Base64 picker must keep file size and MIME in the same selected-file surface")

        contains(basicAuth, "IndexWorkspaceOutputSurface(", "Basic Auth output must use a semantic output surface")
        contains(basicAuth, "workspaceSemantic: .naturalHeightShortResultPanel", "Basic Auth output must select the natural-height short-result semantic")
        doesNotContain(basicAuth, "IndexOutputSurface(text: output", "Basic Auth output must not use the legacy internally scrolling output surface")
        doesNotContain(basicAuth, ".verticallyFilling()", "Basic Auth output panel must not fill the viewport like a query/list workspace")
    }

    @Test func fileTypeDetectorUsesNaturalHeightShortResultPanel() throws {
        let page = try readSource("Sources/XTools/ToolPages/Utility/FileTypeDetectorPage.swift")
        let session = try readSource("Sources/XTools/ToolPages/Utility/FileTypeDetectorSession.swift")
        let dropZone = try readSource("Sources/XTools/Shared/Components/IndexDropZone.swift")
        let sharedComponents = try readSharedBagComponents()

        contains(page, "IndexPage(\"文件类型探测器\", subtitle: \"上传文件，对比扩展名与文件内容证据。\", layout: .scroll)", "File type detector must use the tool page outer scroll owner")
        appearsBefore(page, "IndexPanel(\"上传文件\")", "IndexPanel(\"检测结果\")", "File type detector must keep the upload panel before the result panel")
        contains(page, "IndexWorkspaceResultSurface(workspaceSemantic: .naturalHeightShortResultPanel)", "File type detector results must explicitly select the natural-height short result semantic")
        doesNotContain(page, "ScrollView {", "File type detector results must not use an internal vertical scroll container")
        doesNotContain(page, ".verticallyFilling()", "File type detector result panel must not fill the remaining viewport like a query/list workspace")
        doesNotContain(page, ".queryListWorkspace", "File type detector must not be classified as a query/list workspace")
        doesNotContain(page, "IndexScrollableKV", "File type detector results must not use the scrollable KV query/list helper")
        doesNotContain(page, "IndexScrollableResultCardList", "File type detector results must not use the scrollable card-list helper")
        contains(session, "FileHandle(forReadingFrom: url)", "File type reader must open the selected file through a handle")
        contains(session, "read(upToCount: maxByteCount)", "File type reader must read only the requested bounded prefix")
        contains(session, "maxByteCount: FileTypeDetector.leadingByteLimit", "File type session must use the Core prefix limit for bounded content and header detection")
        doesNotContain(page, "Data(contentsOf: url)", "File type detector must not load the entire selected file into memory")
        doesNotContain(page, "FileHandle(forReadingFrom:", "File type page must not perform synchronous prefix IO")
        doesNotContain(page, "resourceValues(forKeys:", "File type page must not perform synchronous metadata IO")

        contains(page, "@Environment(\\.fileInputPanelClient) private var fileInputPanelClient", "File type page must receive the shared window-scoped input panel client")
        contains(page, "ToolWorkspaceHost(key: FileTypeDetectorSession.workspaceKey)", "File type page state and async work must resolve from the retained detector session")
        contains(page, "@ObservedObject var session: FileTypeDetectorSession", "File type content must observe the retained detector session")
        contains(page, "session.selectFile(filePanel: fileInputPanelClient)", "File type click selection must use the shared panel client")
        contains(page, ".indexDropZone(", "File type upload surface must accept local single-file drops through the shared drop zone")
        contains(dropZone, ".dropDestination(for: URL.self)", "The shared drop zone must own the native drop destination for local single-file drops")
        contains(dropZone, "SingleFileDropResolver.resolve(urls)", "File type drops must use the shared single-file batch resolver")
        contains(page, "onFile: { session.inspect($0) }", "Dropped files must enter the shared detector session handler")
        contains(session, "self.inspect(url)", "Panel-selected and dropped URLs must enter the same detector session handler")
        contains(page, "session.rejectMultipleFileDrop()", "File type drops must reject an entire multi-file batch")
        contains(page, ".indexWorkspaceDiagnostic(session.error)", "File selection and metadata failures must stay on the upload panel that owns the input")
        contains(page, ".indexWorkspaceDiagnostic(session.warning, tone: .warning)", "Prefix-read warnings must stay on the result panel that owns the partial report")
        doesNotContain(page, "session.error ?? session.warning", "Input failures and result warnings must not be collapsed into one sibling-panel diagnostic")
        appearsBefore(page, ".indexWorkspaceDiagnostic(session.error)", "IndexPanel(\"检测结果\")", "The upload diagnostic must be emitted before the result panel begins")
        appearsBefore(page, "IndexPanel(\"检测结果\")", ".indexWorkspaceDiagnostic(session.warning, tone: .warning)", "The prefix warning must be emitted inside the result panel")
        doesNotContain(page, "NSOpenPanel()", "File type page must not construct its own input panel")
        doesNotContain(page, "runModal()", "File type input must not start a synchronous modal event loop")

        contains(session, "workGate.runDetached", "File type metadata and prefix reads must run off the main actor through AsyncWorkGate")
        contains(session, ".isRegularFileKey, .isPackageKey, .fileSizeKey", "File type reader must reject directories and packages before prefix IO")
        contains(session, "workGate.isCurrent(generation)", "File type session must suppress stale background completions")
        contains(session, "case success(FileTypeReport, warning: String?)", "File type prefix warnings must remain separate from metadata failures")

        contains(page, "message: \"选择文件后显示检测结果\"", "File type detector must keep the existing empty result copy inside the canonical empty state")
        contains(page, "Text(indexWrappingAttributedText(session.fileName, lineBreakMode: .byCharWrapping))", "Uploaded file name must wrap long filenames in the upload panel")
        contains(page, "IndexKVRow(key: \"文件名\", value: report.fileName, valueLineBreakMode: .byCharWrapping, valueMotion: .immediate)", "File name result must wrap long filenames within the result panel")
        contains(page, "IndexKVRow(key: \"文件扩展名\", value: report.fileExtension, valueLineBreakMode: .byCharWrapping, valueMotion: .immediate)", "Actual file extension must remain visible")
        contains(page, "IndexKVRow(key: \"扩展名推断 MIME\", value: report.extensionMIMEType, valueLineBreakMode: .byCharWrapping, valueMotion: .immediate)", "Extension evidence must be shown independently")
        contains(page, "IndexKVRow(key: \"内容签名 MIME\", value: report.contentMIMEType, valueLineBreakMode: .byCharWrapping, valueMotion: .immediate)", "Content evidence must be shown independently")
        contains(page, "IndexKVRow(key: \"最终判定 MIME\", value: report.resolvedMIMEType, valueLineBreakMode: .byCharWrapping, valueMotion: .immediate)", "Resolved MIME type must remain explicit")
        contains(page, "IndexKVRow(key: \"文件大小\", value: report.fileSize, valueLineBreakMode: .byCharWrapping, valueMotion: .immediate)", "File size result must stay in the existing order")
        contains(page, "IndexKVRow(key: \"文件头（前 16 字节）\", value: report.headerBytes, valueLineBreakMode: .byCharWrapping, valueMotion: .immediate)", "Header bytes must wrap long values within the result panel")
        doesNotContain(page, "魔数", "File type UI must not describe every displayed header byte as a magic number")
        appearsBefore(page, "IndexKVRow(key: \"文件名\"", "IndexKVRow(key: \"文件扩展名\"", "File name must stay before extension")
        appearsBefore(page, "IndexKVRow(key: \"文件扩展名\"", "IndexKVRow(key: \"扩展名推断 MIME\"", "Actual extension must stay before extension evidence")
        appearsBefore(page, "IndexKVRow(key: \"扩展名推断 MIME\"", "IndexKVRow(key: \"内容签名 MIME\"", "Extension evidence must stay before content evidence")
        appearsBefore(page, "IndexKVRow(key: \"内容签名 MIME\"", "IndexKVRow(key: \"最终判定 MIME\"", "Content evidence must stay before the resolved type")
        appearsBefore(page, "IndexKVRow(key: \"最终判定 MIME\"", "IndexKVRow(key: \"文件大小\"", "Resolved type must stay before file size")
        appearsBefore(page, "IndexKVRow(key: \"文件大小\"", "IndexKVRow(key: \"文件头（前 16 字节）\"", "File size must stay before header bytes")

        contains(sharedComponents, "var valueLineBreakMode: NSLineBreakMode? = .byCharWrapping", "Result rows must wrap long content values by default")
        contains(sharedComponents, "Text(indexWrappingAttributedText(value, lineBreakMode: valueLineBreakMode))", "Result rows must support explicit long-token wrapping")
        contains(sharedComponents, "Text(value)", "Result rows must preserve an explicit nil fallback for plain text rendering")
        contains(sharedComponents, ".fixedSize(horizontal: false, vertical: true)", "Wrapped result values must expand to their natural row height")
    }

    @Test func regexAndCronExposeTheirActualGrammarAndPreviewContext() throws {
        let regex = try readSource("Sources/XTools/ToolPages/Development/RegexTesterPage.swift")
        let cron = try readSource("Sources/XTools/ToolPages/Development/CrontabGeneratorPage.swift")
        let cronCore = try readSource("Sources/XToolsCore/Utility/CronScheduler.swift")

        contains(regex, "使用 ICU 引擎实时测试正则并高亮匹配。", "Regex page must identify the ICU flavor without adding a new panel")
        contains(cron, "每 30 分钟", "Crontab presets must replace the misleading every-five-days label with an unambiguous schedule")
        doesNotContain(cron, "每 5 天", "Crontab must not describe day-of-month stepping as a continuous five-day interval")
        contains(cron, "CronScheduler.dayMatchingExplanation(workspace.expression)", "Crontab page must render Core's Unix day-field OR explanation")
        contains(cronCore, "日与星期字段同时受限时，任一字段匹配即运行", "Cron Core must own the user-facing Unix day-field OR semantics")
        contains(cron, "TimeZone.current.identifier", "Crontab next-run preview must expose the timezone used for calculation")
    }

    @Test func chmodPageKeepsBidirectionalInputAndSpecialBitsCompact() throws {
        let source = try readSource("Sources/XTools/ToolPages/Development/ChmodCalculatorPage.swift")

        contains(source, "IndexTextInput(placeholder: \"644 或 4755\"", "Chmod page must accept direct octal input")
        contains(source, "IndexSwitch(title: \"setuid\"", "Chmod page must expose setuid")
        contains(source, "IndexSwitch(title: \"setgid\"", "Chmod page must expose setgid")
        contains(source, "IndexSwitch(title: \"sticky\"", "Chmod page must expose sticky")
        contains(source, ".indexWorkspaceDiagnostic(workspace.error)", "Invalid chmod input must use the workspace diagnostic surface")
        doesNotContain(source, "capabilityWarning", "Chmod no longer needs a warning that special bits are unsupported")
    }

    @Test func randomPortPageDisclosesRangeAndDisablesEmptyCopy() throws {
        let source = try readSource("Sources/XTools/ToolPages/Development/RandomPortPage.swift")
        let heroStat = try readSource("Sources/XTools/Shared/Components/IndexHeroStat.swift")

        contains(source, "\"随机端口\",", "Random-port page must use the product name")
        contains(source, "生成 1024-65535 范围内的随机端口号。", "Random-port page must disclose its generation range")
        contains(source, "IndexHeroStat(value: workspace.output ?? \"尚未生成\", tone: workspace.output == nil ? .primary : .accent, copyable: workspace.output != nil, design: .rounded)", "Random-port results must render through the shared hero stat with rounded personality and copy unavailable before generation")
        contains(heroStat, "if copyable && !value.isEmpty {", "The shared hero stat must suppress its copy affordance while no value is available")
        contains(heroStat, "IndexCopyButton(text: value, iconOnly: true)", "The shared hero stat must own the copy action through the shared copy button")
        doesNotContain(source, "AvailableTCPPortAllocator", "Random-port page must not probe a socket")
    }

    @Test func crontabUsesScrollablePageLayout() throws {
        let source = try readSource("Sources/XTools/ToolPages/Development/CrontabGeneratorPage.swift")

        contains(source, "IndexPage(\"Crontab 生成\", subtitle: \"用预设拼出 cron 表达式并给出说明。\", workspaceSemantic: .naturalHeightShortResultPanel)", "Crontab page must use the natural-height short-result shell")
        contains(source, "\"星期 (0-7)\"", "Crontab weekday label must match Core support for 0 and 7 as Sunday")
        contains(source, "IndexShortResultKV(rows: rows, emptyText: explanationEmptyText, copyable: false, valueMotion: .immediate)", "Crontab explanation must route its cron-aware placeholder through shared bounded presence")
        contains(source, "? \"@reboot 会在系统启动时执行，没有固定日历预览\"", "Crontab @reboot must be treated as valid but without calendar preview")
    }
}

extension QueryListAndUtilitySourceContractTests {
    @Test func queryPagesUseSharedShellAndStaticPanelContracts() throws {
        let pages: [(String, String)] = [
            ("HTTP status", try readSource("Sources/XTools/ToolPages/Web/HTTPStatusCodesPage.swift")),
            ("Device information", try readSource("Sources/XTools/ToolPages/Utility/DeviceInformationPage.swift")),
            ("Timezone viewer", try readSource("Sources/XTools/ToolPages/Time/TimezoneViewerPage.swift"))
        ]

        for (name, source) in pages {
            contains(source, "workspaceSemantic: .queryListWorkspace", "\(name) must use the shared query-list page shell")
            contains(source, ".withoutDiagnosticStatusSlot()", "\(name) static panels must opt out of the diagnostic reserve")
            doesNotContain(source, ".buttonStyle(.bordered", "\(name) must not introduce native bordered button chrome")
            doesNotContain(source, "ProgressView(", "\(name) must use shared progress/empty owners instead of a bare progress view")
        }
    }
}
